### ISSUE TITLE
500 internal server error and clearing the template cache

### ISSUE THREAD

**Issue by schnubor** [octobercms/october#1422]
Hi all,

had an issue with my october the last 2 days. I changed nothing and a 500 internal server error showed up out of nowhere. I thought my provider messed something up, because the site was working again after 12h of downtime. I did nothing. It happened again the following day. So I assumed some sort of faulty cache caused the problem in the first place. The faulty cache ran out and it worked again. But this is just an assumption. 

However, with my fresh 500 internal server error I cleared the `storage/cms/cache`, `/storage/cms/combiner` and `storage/cms/twig` manually and it worked again. The funny thing is, that `php artisan cache:clear` just cleared the Application cache, but not the Template cache – any ideas why?

So after manually clearing the template cache the 500 is gone. My site is hosted at fortrabbit.com and to my support ticket they replied that other costumers with octobercms had the same issue in the past. They also lead me to deleting the cache files manually.

Would be happy to hear some thoughts on that, since this is a pretty major issue from my perspective.

Thanks,
Christian

**Comment by vojtasvoboda** [comment]
I had same problem twice in last month but still don't know, what is the problem. Just clear cache and 500 is gone.

For complete clear cache I recommend plugin http://octobercms.com/plugin/romanov-clearcachewidget.

**Comment by Teranode** [comment]
probably because there is also a:
```
view:clear
```
command for artisan

**Comment by schnubor** [comment]
No, there isn't.

**Comment by Teranode** [comment]
okay so u mean to tell me:
![artisan commands](http://i.imgur.com/4EwBn8g.png)

doesn't exist and its a mere fabrication?

**Comment by schnubor** [comment]
No I didn't mean that.I just don't have it.

![artisan](http://i.imgur.com/sxA4NqD.png)

**Comment by Teranode** [comment]
that's rather odd then. It's on both my Laravel 5.0.* and 5.1.* instances.

**Comment by vojtasvoboda** [comment]
So your solution is clean cache once a week to prevent error from cache? :-)

**Comment by Teranode** [comment]
Well if you provide me an error log when it happens again i might be able to know/fix the problem. I get 500 error logs all them time (because i keep breaking the routes and other random things for testing purposes)

**Comment by schnubor** [comment]
Rather odd indead @Teranode . I also have it in my Laravel 5+ projects but not in October for whatever reason. Happy to provide the error log once it happens again. Thanks! 

@vojtasvoboda since I cleaned the cache manually it didn't break again. The bad thing is, that it happened in the first place.

**Comment by vojtasvoboda** [comment]
Yesterday I got internal server error again after 2 weeks without any error. Here is the error msg with call-stack (any domain occurrences replaced by mysite.com):

```
exception 'ErrorException' with message 'unserialize(): Error at offset 2 of 24566 bytes' in /usr/local/www/data/mysite.com/www/vendor/laravel/framework/src/Illuminate/Cache/FileStore.php:79
Stack trace:
#0 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(8, 'unserialize(): ...', '/usr/local/www/...', 79, Array)
#1 /usr/local/www/data/mysite.com/www/vendor/laravel/framework/src/Illuminate/Cache/FileStore.php(79): unserialize('s:51173:"a:31:{...')
#2 /usr/local/www/data/mysite.com/www/vendor/laravel/framework/src/Illuminate/Cache/FileStore.php(44): Illuminate\Cache\FileStore->getPayload('2126007312snipp...')
#3 /usr/local/www/data/mysite.com/www/vendor/laravel/framework/src/Illuminate/Cache/Repository.php(95): Illuminate\Cache\FileStore->get('2126007312snipp...')
#4 [internal function]: Illuminate\Cache\Repository->get('2126007312snipp...', false)
#5 /usr/local/www/data/mysite.com/www/vendor/laravel/framework/src/Illuminate/Cache/CacheManager.php(312): call_user_func_array(Array, Array)
#6 /usr/local/www/data/mysite.com/www/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(213): Illuminate\Cache\CacheManager->__call('get', Array)
#7 /usr/local/www/data/mysite.com/www/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(213): Illuminate\Cache\CacheManager->get('2126007312snipp...', false)
#8 /usr/local/www/data/mysite.com/www/plugins/rainlab/pages/classes/Snippet.php(499): Illuminate\Support\Facades\Facade::__callStatic('get', Array)
#9 /usr/local/www/data/mysite.com/www/plugins/rainlab/pages/classes/Snippet.php(499): Illuminate\Support\Facades\Cache::get('2126007312snipp...', false)
#10 /usr/local/www/data/mysite.com/www/plugins/rainlab/pages/classes/Snippet.php(197): RainLab\Pages\Classes\Snippet::extractSnippetsFromMarkupCached(Object(Cms\Classes\Theme), 'en-services-mee...', '<figure data-co...')
#11 /usr/local/www/data/mysite.com/www/plugins/rainlab/pages/classes/Page.php(474): RainLab\Pages\Classes\Snippet::processPageMarkup('en-services-mee...', Object(Cms\Classes\Theme), '<figure data-co...')
#12 /usr/local/www/data/mysite.com/www/plugins/rainlab/pages/classes/Controller.php(98): RainLab\Pages\Classes\Page->getProcessedPlaceholderMarkup('boxb1', '<figure data-co...')
#13 /usr/local/www/data/mysite.com/www/plugins/rainlab/pages/Plugin.php(125): RainLab\Pages\Classes\Controller->getPlaceholderContents(Object(Cms\Classes\Page), 'boxb1', '<figure data-co...')
#14 [internal function]: RainLab\Pages\Plugin->RainLab\Pages\{closure}('boxb1', '<figure data-co...')
#15 /usr/local/www/data/mysite.com/www/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php(218): call_user_func_array(Object(Closure), Array)
#16 /usr/local/www/data/mysite.com/www/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(216): Illuminate\Events\Dispatcher->fire('cms.block.rende...', Array, true)
#17 /usr/local/www/data/mysite.com/www/modules/cms/twig/Extension.php(221): Illuminate\Support\Facades\Facade::__callStatic('fire', Array)
#18 /usr/local/www/data/mysite.com/www/modules/cms/twig/Extension.php(221): Illuminate\Support\Facades\Event::fire('cms.block.rende...', Array, true)
#19 /usr/local/www/data/mysite.com/www/storage/cms/twig/2/4/24339d69a962e7944b2127c6e13bfe6790282144813dceb23abc96030a005df0.php(170): Cms\Twig\Extension->displayBlock('boxb1', NULL)
#20 /usr/local/www/data/mysite.com/www/vendor/twig/twig/lib/Twig/Template.php(365): __TwigTemplate_bfc2cf6fc03f946725be56af5fe02b60c7cab46d4e8b2df7b346d6b97e9f587b->doDisplay(Array, Array)
#21 /usr/local/www/data/mysite.com/www/vendor/twig/twig/lib/Twig/Template.php(339): Twig_Template->displayWithErrorHandling(Array, Array)
#22 /usr/local/www/data/mysite.com/www/vendor/twig/twig/lib/Twig/Template.php(350): Twig_Template->display(Array)
#23 /usr/local/www/data/mysite.com/www/modules/cms/classes/Controller.php(381): Twig_Template->render(Array)
#24 /usr/local/www/data/mysite.com/www/modules/cms/classes/Controller.php(209): Cms\Classes\Controller->runPage(Object(Cms\Classes\Page))
#25 /usr/local/www/data/mysite.com/www/modules/cms/classes/CmsController.php(47): Cms\Classes\Controller->run('en/experience/m...')
#26 [internal function]: Cms\Classes\CmsController->run('en/experience/m...')
#27 /usr/local/www/data/mysite.com/www/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(246): call_user_func_array(Array, Array)
#28 /usr/local/www/data/mysite.com/www/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(162): Illuminate\Routing\Controller->callAction('run', Array)
#29 /usr/local/www/data/mysite.com/www/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(107): Illuminate\Routing\ControllerDispatcher->call(Object(Cms\Classes\CmsController), Object(Illuminate\Routing\Route), 'run')
#30 [internal function]: Illuminate\Routing\ControllerDispatcher->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#31 /usr/local/www/data/mysite.com/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(141): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#32 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#33 /usr/local/www/data/mysite.com/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(101): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#34 /usr/local/www/data/mysite.com/www/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(108): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#35 /usr/local/www/data/mysite.com/www/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(67): Illuminate\Routing\ControllerDispatcher->callWithinStack(Object(Cms\Classes\CmsController), Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request), 'run')
#36 /usr/local/www/data/mysite.com/www/vendor/laravel/framework/src/Illuminate/Routing/Route.php(204): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request), 'Cms\Classes\Cms...', 'run')
#37 /usr/local/www/data/mysite.com/www/vendor/laravel/framework/src/Illuminate/Routing/Route.php(134): Illuminate\Routing\Route->runWithCustomDispatcher(Object(Illuminate\Http\Request))
#38 /usr/local/www/data/mysite.com/www/vendor/laravel/framework/src/Illuminate/Routing/Router.php(701): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#39 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#40 /usr/local/www/data/mysite.com/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(141): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#41 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#42 /usr/local/www/data/mysite.com/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(101): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#43 /usr/local/www/data/mysite.com/www/vendor/laravel/framework/src/Illuminate/Routing/Router.php(703): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#44 /usr/local/www/data/mysite.com/www/vendor/laravel/framework/src/Illuminate/Routing/Router.php(670): Illuminate\Routing\Router->runRouteWithinStack(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request))
#45 /usr/local/www/data/mysite.com/www/vendor/laravel/framework/src/Illuminate/Routing/Router.php(628): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#46 /usr/local/www/data/mysite.com/www/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(214): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#47 [internal function]: Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}(Object(Illuminate\Http\Request))
#48 /usr/local/www/data/mysite.com/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(141): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#49 /usr/local/www/data/mysite.com/www/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(55): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#50 /usr/local/www/data/mysite.com/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(125): Illuminate\View\Middleware\ShareErrorsFromSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#51 /usr/local/www/data/mysite.com/www/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(61): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#52 /usr/local/www/data/mysite.com/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(125): Illuminate\Session\Middleware\StartSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#53 /usr/local/www/data/mysite.com/www/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(36): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#54 /usr/local/www/data/mysite.com/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(125): Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse->handle(Object(Illuminate\Http\Request), Object(Closure))
#55 /usr/local/www/data/mysite.com/www/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(40): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#56 /usr/local/www/data/mysite.com/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(125): Illuminate\Cookie\Middleware\EncryptCookies->handle(Object(Illuminate\Http\Request), Object(Closure))
#57 /usr/local/www/data/mysite.com/www/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(42): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#58 /usr/local/www/data/mysite.com/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(125): Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle(Object(Illuminate\Http\Request), Object(Closure))
#59 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#60 /usr/local/www/data/mysite.com/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(101): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#61 /usr/local/www/data/mysite.com/www/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(115): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#62 /usr/local/www/data/mysite.com/www/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(84): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#63 /usr/local/www/data/mysite.com/www/index.php(44): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#64 {main}

Next exception 'Twig_Error_Runtime' with message 'An exception has been thrown during the rendering of a template ("unserialize(): Error at offset 2 of 24566 bytes") in "/usr/local/www/data/mysite.com/www/themes/mysitecom/layouts/content-left.htm" at line 79.' in /usr/local/www/data/mysite.com/www/vendor/twig/twig/lib/Twig/Template.php:380
Stack trace:
#0 /usr/local/www/data/mysite.com/www/vendor/twig/twig/lib/Twig/Template.php(339): Twig_Template->displayWithErrorHandling(Array, Array)
#1 /usr/local/www/data/mysite.com/www/vendor/twig/twig/lib/Twig/Template.php(350): Twig_Template->display(Array)
#2 /usr/local/www/data/mysite.com/www/modules/cms/classes/Controller.php(381): Twig_Template->render(Array)
#3 /usr/local/www/data/mysite.com/www/modules/cms/classes/Controller.php(209): Cms\Classes\Controller->runPage(Object(Cms\Classes\Page))
#4 /usr/local/www/data/mysite.com/www/modules/cms/classes/CmsController.php(47): Cms\Classes\Controller->run('en/experience/m...')
#5 [internal function]: Cms\Classes\CmsController->run('en/experience/m...')
#6 /usr/local/www/data/mysite.com/www/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(246): call_user_func_array(Array, Array)
#7 /usr/local/www/data/mysite.com/www/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(162): Illuminate\Routing\Controller->callAction('run', Array)
#8 /usr/local/www/data/mysite.com/www/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(107): Illuminate\Routing\ControllerDispatcher->call(Object(Cms\Classes\CmsController), Object(Illuminate\Routing\Route), 'run')
#9 [internal function]: Illuminate\Routing\ControllerDispatcher->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#10 /usr/local/www/data/mysite.com/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(141): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#11 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#12 /usr/local/www/data/mysite.com/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(101): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#13 /usr/local/www/data/mysite.com/www/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(108): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#14 /usr/local/www/data/mysite.com/www/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(67): Illuminate\Routing\ControllerDispatcher->callWithinStack(Object(Cms\Classes\CmsController), Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request), 'run')
#15 /usr/local/www/data/mysite.com/www/vendor/laravel/framework/src/Illuminate/Routing/Route.php(204): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request), 'Cms\Classes\Cms...', 'run')
#16 /usr/local/www/data/mysite.com/www/vendor/laravel/framework/src/Illuminate/Routing/Route.php(134): Illuminate\Routing\Route->runWithCustomDispatcher(Object(Illuminate\Http\Request))
#17 /usr/local/www/data/mysite.com/www/vendor/laravel/framework/src/Illuminate/Routing/Router.php(701): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#18 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#19 /usr/local/www/data/mysite.com/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(141): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#20 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#21 /usr/local/www/data/mysite.com/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(101): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#22 /usr/local/www/data/mysite.com/www/vendor/laravel/framework/src/Illuminate/Routing/Router.php(703): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#23 /usr/local/www/data/mysite.com/www/vendor/laravel/framework/src/Illuminate/Routing/Router.php(670): Illuminate\Routing\Router->runRouteWithinStack(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request))
#24 /usr/local/www/data/mysite.com/www/vendor/laravel/framework/src/Illuminate/Routing/Router.php(628): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#25 /usr/local/www/data/mysite.com/www/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(214): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#26 [internal function]: Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}(Object(Illuminate\Http\Request))
#27 /usr/local/www/data/mysite.com/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(141): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#28 /usr/local/www/data/mysite.com/www/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(55): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#29 /usr/local/www/data/mysite.com/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(125): Illuminate\View\Middleware\ShareErrorsFromSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#30 /usr/local/www/data/mysite.com/www/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(61): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#31 /usr/local/www/data/mysite.com/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(125): Illuminate\Session\Middleware\StartSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#32 /usr/local/www/data/mysite.com/www/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(36): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#33 /usr/local/www/data/mysite.com/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(125): Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse->handle(Object(Illuminate\Http\Request), Object(Closure))
#34 /usr/local/www/data/mysite.com/www/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(40): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#35 /usr/local/www/data/mysite.com/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(125): Illuminate\Cookie\Middleware\EncryptCookies->handle(Object(Illuminate\Http\Request), Object(Closure))
#36 /usr/local/www/data/mysite.com/www/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(42): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#37 /usr/local/www/data/mysite.com/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(125): Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle(Object(Illuminate\Http\Request), Object(Closure))
#38 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#39 /usr/local/www/data/mysite.com/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(101): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#40 /usr/local/www/data/mysite.com/www/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(115): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#41 /usr/local/www/data/mysite.com/www/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(84): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#42 /usr/local/www/data/mysite.com/www/index.php(44): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#43 {main}
```

**Comment by Teranode** [comment]
Sigh, i hate when laravel cuts off

anyway take a look at
```
/usr/local/www/data/mysite.com/www/themes/mysitecom/layouts/content-left.htm
```

I don't know whats in it so i can't help there. This problem is probably a general problem with the twig integration and cache config. I can't really fix this unless i am experiencing the error myself, which I don't get.

If you can provide me with the code for the "content-left.htm"
While you are at it try to see if you can generate a new laravel key:
```
artisan key:generate
```
and then clear the cache (since the new key will most certainly break encrypted cookies/sessions/serialized views)

**Comment by daftspunk** [comment]
Laravel's file based cache is becoming increasingly unreliable. Until we find a suitable way to address it,  you can try using a different cache driver, like the database driver.

**Comment by schnubor** [comment]
Thanks @daftspunk ! Will try that :)

**Comment by schnubor** [comment]
@daftspunk Hey, I switched a couple of sites from file to database caching. Sometimes I got a "invalid data" exception. Googled that and found this: http://stackoverflow.com/questions/29770790/laravel-cache-invalid-data

Changed to `value` column of the cache table to LONGTEXT for those that were not working and voià, that helped. So I thought maybe it would be good to update the migration of the cache table to use LONGTEXT instead of TEXT. 

Cheers,
Christian

**Comment by vojtasvoboda** [comment]
I also tried to switch from file to database caching and got:

![snimek obrazovky 2015-11-18 v 16 20 59](https://cloud.githubusercontent.com/assets/374917/11452100/08a41346-95dc-11e5-91e7-ab17b83cc6de.png)

**Comment by schnubor** [comment]
@vojtasvoboda yes, exactly that. Can you try changing the fix I mentioned earlier: changing the type of the value column in the cache table in your db to LONGTEXT instead of TEXT?

**Comment by daftspunk** [comment]
Is this still an issue in the October stable release? We made some improvements to the unserialization logic.

**Comment by daftspunk** [comment]
Making #1250 master for this

**Comment by shoguniphicus** [comment]
Changing MySQL cache table column type for "value" to MEDTEXT or LONGTEXT eliminates the problem for me.

**Comment by daftspunk** [comment]
@shoguniphicus changed this in 4c39b340fe24bef873631d2fea56f65cfbecdbd8 for future installs. Thanks
