### ISSUE TITLE
In develop branch artisan october:up broken

### ISSUE THREAD

**Issue by Arekusei** [octobercms/october#1897]
1. composer create-project october/october dev dev-develop
2. artisan october:up
3. Gain exception
```
  [Illuminate\Database\QueryException]
  SQLSTATE[42S02]: Base table or view not found: 1146 Table 'database_dev.system_parameters' doesn't exist (SQL: select `value` from `system_p
  arameters` where `namespace` = cms and `group` = theme and `item` = active limit 1)

  [PDOException]
  SQLSTATE[42S02]: Base table or view not found: 1146 Table 'database_dev.system_parameters' doesn't exist
```

This code reads the configuration before the create the database.
https://github.com/octobercms/october/blob/develop/modules/cms/ServiceProvider.php#L51
https://github.com/octobercms/october/blob/develop/modules/cms/classes/Theme.php#L152

**Comment by Arekusei** [comment]
May be needed something like this
```php
        if (!$this->app->runningInConsole()) {
            $this->bootDefaultTheme();
        }
```
for this https://github.com/octobercms/october/blob/develop/modules/cms/ServiceProvider.php#L51

**Comment by Arekusei** [comment]
Part of stack trace
```
#9 E:\User\Workspace\Projects\greatstone\dev\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Builder.php(273): Illuminate\Database\Eloquent\Builder->value('value')
#10 E:\User\Workspace\Projects\greatstone\dev\modules\cms\classes\Theme.php(152): Illuminate\Database\Eloquent\Builder->pluck('value')
#11 E:\User\Workspace\Projects\greatstone\dev\vendor\laravel\framework\src\Illuminate\Cache\Repository.php(206): Cms\Classes\Theme::Cms\Classes\{closure}()
#12 [internal function]: Illuminate\Cache\Repository->remember('cms::theme.acti...', 1440, Object(Closure))
#13 E:\User\Workspace\Projects\greatstone\dev\vendor\laravel\framework\src\Illuminate\Cache\CacheManager.php(318): call_user_func_array(Array, Array)
#14 E:\User\Workspace\Projects\greatstone\dev\vendor\laravel\framework\src\Illuminate\Support\Facades\Facade.php(222): Illuminate\Cache\CacheManager->__call('remember', Array)
#15 E:\User\Workspace\Projects\greatstone\dev\vendor\laravel\framework\src\Illuminate\Support\Facades\Facade.php(222): Illuminate\Cache\CacheManager->remember('cms::theme.acti...', 1440, Object(Closure))
#16 E:\User\Workspace\Projects\greatstone\dev\modules\cms\classes\Theme.php(153): Illuminate\Support\Facades\Facade::__callStatic('remember', Array)
#17 E:\User\Workspace\Projects\greatstone\dev\modules\cms\classes\Theme.php(153): Illuminate\Support\Facades\Cache::remember('cms::theme.acti...', 1440, Object(Closure))
#18 E:\User\Workspace\Projects\greatstone\dev\modules\cms\ServiceProvider.php(301): Cms\Classes\Theme::getActiveThemeCode()
#19 E:\User\Workspace\Projects\greatstone\dev\modules\cms\ServiceProvider.php(51): Cms\ServiceProvider->bootDefaultTheme()
#20 [internal function]: Cms\ServiceProvider->boot()
```

**Comment by Almusamim** [comment]
1+

**Comment by daftspunk** [comment]
Hopefully fixed in Build 320. Please try again.

**Comment by Arekusei** [comment]
Ok. Check on time appears.
Thanks.
