### ISSUE TITLE
Template Rendering issue with latest version

### ISSUE THREAD

**Issue by chrisvidal** [octobercms/october#2224]
````An exception has been thrown during the rendering of a template ("Call to undefined method October\Rain\Halcyon\Builder::useCache()").````

**Comment by daftspunk** [comment]
More information please. See Contribution guidelines.

**Comment by chrisvidal** [comment]
template line in question
````<td><a href="{{ invoice.url }}">{{ invoice.getUniqueId }}</a></td>````

trace log is as followed:

````
[2016-07-18 14:58:53] dev.ERROR: exception 'BadMethodCallException' with message 'Call to undefined method October\Rain\Halcyon\Builder::useCache()' in /Users/chrisvidal/Sites/smartbuild.asia/site/vendor/october/rain/src/Halcyon/Builder.php:769
Stack trace:
#0 [internal function]: October\Rain\Halcyon\Builder->__call('useCache', Array)
#1 [internal function]: October\Rain\Halcyon\Builder->useCache()
#2 /Users/chrisvidal/Sites/smartbuild.asia/site/vendor/october/rain/src/Halcyon/Model.php(1643): call_user_func_array(Array, Array)
#3 /Users/chrisvidal/Sites/smartbuild.asia/site/modules/cms/Classes/CmsCompoundObject.php(489): October\Rain\Halcyon\Model->__call('useCache', Array)
#4 [internal function]: Cms\Classes\CmsCompoundObject->__call('useCache', Array)
#5 [internal function]: Cms\Classes\Page->useCache()
#6 /Users/chrisvidal/Sites/smartbuild.asia/site/vendor/october/rain/src/Halcyon/Model.php(1658): call_user_func_array(Array, Array)
#7 /Users/chrisvidal/Sites/smartbuild.asia/site/plugins/labz/payment/traits/UrlMaker.php(77): October\Rain\Halcyon\Model::__callStatic('useCache', Array)
#8 /Users/chrisvidal/Sites/smartbuild.asia/site/plugins/labz/payment/traits/UrlMaker.php(77): Cms\Classes\Page::useCache()
#9 /Users/chrisvidal/Sites/smartbuild.asia/site/plugins/labz/payment/traits/UrlMaker.php(108): Labz\Payment\Models\Invoice->getUrlPageName()
#10 /Users/chrisvidal/Sites/smartbuild.asia/site/plugins/labz/payment/traits/UrlMaker.php(37): Labz\Payment\Models\Invoice->makeUrl()
#11 /Users/chrisvidal/Sites/smartbuild.asia/site/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(2700): Labz\Payment\Models\Invoice->getUrlAttribute(NULL)````

**Comment by daftspunk** [comment]
It would appear the author of `Labz\Payment` has forked the Pay plugin. See this commit for the fix:

https://github.com/responsiv/pay-plugin/commit/f26c4edf157e696549cdaeec8213e381243429f0
