### ISSUE TITLE
Url database field too small for request logs.

### ISSUE THREAD

**Issue by tschallacka** [octobercms/october#2888]
##### Expected behavior
Saving all url requests to request log

##### Actual behavior
```exception 'PDOException' with message 'SQLSTATE[22001]: [Microsoft][ODBC Driver 11 for SQL Server][SQL Server]String or binary data would be truncated.' in ....\vendor\laravel\framework\src\Illuminate\Database\Connection.php:362
Stack trace:
#0 ....\vendor\laravel\framework\src\Illuminate\Database\Connection.php(362): PDOStatement->execute(Array)
#1 ....\vendor\laravel\framework\src\Illuminate\Database\Connection.php(614): Illuminate\Database\Connection->Illuminate\Database\{closure}(Object(Illuminate\Database\SqlServerConnection), 'insert into [sy...', Array)
#2 ....\vendor\laravel\framework\src\Illuminate\Database\Connection.php(578): Illuminate\Database\Connection->runQueryCallback('insert into [sy...', Array, Object(Closure))
#3 ....\vendor\laravel\framework\src\Illuminate\Database\Connection.php(363): Illuminate\Database\Connection->run('insert into [sy...', Array, Object(Closure))
#4 ....\vendor\laravel\framework\src\Illuminate\Database\Connection.php(320): Illuminate\Database\Connection->statement('insert into [sy...', Array)
#5 ....\vendor\laravel\framework\src\Illuminate\Database\Query\Processors\SqlServerProcessor.php(18): Illuminate\Database\Connection->insert('insert into [sy...', Array)
#6 ....\vendor\laravel\framework\src\Illuminate\Database\Query\Builder.php(1732): Illuminate\Database\Query\Processors\SqlServerProcessor->processInsertGetId(Object(October\Rain\Database\QueryBuilder), 'insert into [sy...', Array, 'id')
#7 [internal function]: Illuminate\Database\Query\Builder->insertGetId(Array, 'id')
#8 ....\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Builder.php(936): call_user_func_array(Array, Array)
#9 ....\vendor\october\rain\src\Database\Builder.php(131): Illuminate\Database\Eloquent\Builder->__call('insertGetId', Array)
#10 ....\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Model.php(1608): October\Rain\Database\Builder->__call('insertGetId', Array)
#11 ....\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Model.php(1608): October\Rain\Database\Builder->insertGetId(Array, 'id')
#12 ....\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Model.php(1578): Illuminate\Database\Eloquent\Model->insertAndSetId(Object(October\Rain\Database\Builder), Array)
#13 ....\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Model.php(1485): Illuminate\Database\Eloquent\Model->performInsert(Object(October\Rain\Database\Builder), Array)
#14 ....\vendor\october\rain\src\Database\Model.php(1069): Illuminate\Database\Eloquent\Model->save(Array)
#15 ....\vendor\october\rain\src\Database\Model.php(1115): October\Rain\Database\Model->saveInternal(NULL, Array)
#16 ....\modules\system\models\RequestLog.php(51): October\Rain\Database\Model->save()
#17 ....\modules\cms\classes\Controller.php(197): System\Models\RequestLog::add()
#18 ....\modules\cms\classes\CmsController.php(47): Cms\Classes\Controller->run('reizen/canada/k...')
```
Urls for all intents and purposes can be up to 2048 characters long. The default url length for the log is 254 in sql server.
It should be 2048. This causes errors when urls are too long with funny warnings and such.

##### Reproduce steps
use sql server as database
make page with longer than 254 url
access it via the natural way.
Error entry will appear

##### Fix by:
https://github.com/octobercms/october/blob/master/modules/system/database/migrations/2014_10_01_000012_Db_System_Request_Logs.php#L14

Needs to be modified to support 2048 long urls. string(2048) for sql server. but I don't know about other databases.

https://stackoverflow.com/questions/417142/what-is-the-maximum-length-of-a-url-in-different-browsers#417184

**Comment by LukeTowers** [comment]
@tschallacka feel free to make a PR for this change.

**Comment by NemoD503** [comment]
Sorry for spam with some incorrect commits :(
I've made [PR](https://github.com/octobercms/october/pull/3205) for this issue.
