### ISSUE TITLE
OctoberCMS update build from 419 to 426

### ISSUE THREAD

**Issue by MyhedinZika** [octobercms/october#3221]
I was trying to update october from build 419 to 426
I turned on edgeUpdates from false to true

Then on cmd, I did php artistan down, then wrote php artisan october:update

On cmd it showed like this
D:\xampp\htdocs\ora>php artisan october:update
Updating October...
Found 2 new updates!
Downloading application files
Downloading plugin: API-Generator
Unpacking application files
Unpacking plugin: API-Generator
PHP Fatal error:  Uncaught Error: Class name must be a valid object or a string in D:\xampp\htdocs\ora\vendor\laravel\framework\src\Illuminate\Foundation\Exceptions\Handler.php:139
Stack trace:
#0 [internal function]: Illuminate\Foundation\Exceptions\Handler->Illuminate\Foundation\Exceptions\{closure}(0, 'October\\Rain\\Ex...')
#1 D:\xampp\htdocs\ora\vendor\laravel\framework\src\Illuminate\Support\Arr.php(153): call_user_func(Object(Closure), 0, 'October\\Rain\\Ex...')
#2 D:\xampp\htdocs\ora\vendor\laravel\framework\src\Illuminate\Foundation\Exceptions\Handler.php(140): Illuminate\Support\Arr::first(Array, Object(Closure))
#3 D:\xampp\htdocs\ora\vendor\october\rain\src\Foundation\Exception\Handler.php(45): Illuminate\Foundation\Exceptions\Handler->shouldntReport(Object(Symfony\Component\Debug\Exception\FatalThrowableError))
#4 D:\xampp\htdocs\ora\vendor\laravel\framework\src\Illuminate\Foundation\Bootstrap\HandleExceptions.php(79): October\Rain\Foundation\Exception\Handler->report(Object(Symfony\Component\Debug\Exception\Fatal in D:\xampp\htdocs\ora\vendor\laravel\framework\src\Illuminate\Foundation\Exceptions\Handler.php on line 139
PHP Fatal error:  Uncaught Error: Class name must be a valid object or a string in D:\xampp\htdocs\ora\vendor\laravel\framework\src\Illuminate\Foundation\Exceptions\Handler.php:139
Stack trace:
#0 [internal function]: Illuminate\Foundation\Exceptions\Handler->Illuminate\Foundation\Exceptions\{closure}(0, 'October\\Rain\\Ex...')
#1 D:\xampp\htdocs\ora\vendor\laravel\framework\src\Illuminate\Support\Arr.php(153): call_user_func(Object(Closure), 0, 'October\\Rain\\Ex...')
#2 D:\xampp\htdocs\ora\vendor\laravel\framework\src\Illuminate\Foundation\Exceptions\Handler.php(140): Illuminate\Support\Arr::first(Array, Object(Closure))
#3 D:\xampp\htdocs\ora\vendor\october\rain\src\Foundation\Exception\Handler.php(45): Illuminate\Foundation\Exceptions\Handler->shouldntReport(Object(Symfony\Component\Debug\Exception\FatalErrorException))
#4 D:\xampp\htdocs\ora\vendor\laravel\framework\src\Illuminate\Foundation\Bootstrap\HandleExceptions.php(79): October\Rain\Foundation\Exception\Handler->report(Object(Symfony\Component\Debug\Exception\Fatal in D:\xampp\htdocs\ora\vendor\laravel\framework\src\Illuminate\Foundation\Exceptions\Handler.php on line 139

When I did php artisan up, this showed up on my screen
Class 'System\Twig\MediaLibrary' not found

Any idea how to fix this, or what I'm doing wrong?

**Comment by MyhedinZika** [comment]
Nvm close this, looks like I found the issue on another issue that was reported by someone else

My apologies for not checking other issues
