### ISSUE TITLE
ErrorException: putenv() has been disabled for security reasons

### ISSUE THREAD

**Issue by jan-vince** [octobercms/october#3339]
##### Expected behavior
Backed forms should be saved without any errors.

##### Actual behavior
After update to version 431, some backend forms throw error:

````
ErrorException: putenv() has been disabled for security reasons in .../vendor/symfony/console/Application.php:110
````

This is related to PHP configuration of my host that do not allow ````putenv()````.

I understand that I can change hosting company but disabled ````putenv()```` is probably more common situation and many more OctoberCMS users can be affected by this.

As this is related to Symfony package we probably cannot do much about it here but maybe someone has an experience with this and can help.

*Maybe ability to bypass Symfony/console on such hosts?*

##### October build
431

**Comment by LukeTowers** [comment]
@jan-vince it would be helpful if you could provide the full stack trace of the issue.

**Comment by jan-vince** [comment]
Sure, here is one of them (from backend Settings - while saving Log settings).

*When I comment all ````putenv()```` calls in ````.../symfony/console/Application.php````, everything is fine and I can save all forms.*

*I don't know yet how (and why) the symfony console package is used while saving backend forms.*

````
ErrorException: putenv() has been disabled for security reasons in /data/web/virtuals/166926/virtual/www/subdom/rezidencebilylev/vendor/symfony/console/Application.php:110
Stack trace:
#0 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(2, 'putenv() has be...', '/data/web/virtu...', 110, Array)
#1 /data/web/virtuals/166926/virtual/www/subdom/rezidencebilylev/vendor/symfony/console/Application.php(110): putenv('LINES=50')
#2 /data/web/virtuals/166926/virtual/www/subdom/rezidencebilylev/vendor/laravel/framework/src/Illuminate/Console/Application.php(88): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArrayInput), Object(Symfony\Component\Console\Output\BufferedOutput))
#3 /data/web/virtuals/166926/virtual/www/subdom/rezidencebilylev/vendor/laravel/framework/src/Illuminate/Console/Application.php(177): Illuminate\Console\Application->run(Object(Symfony\Component\Console\Input\ArrayInput), Object(Symfony\Component\Console\Output\BufferedOutput))
#4 /data/web/virtuals/166926/virtual/www/subdom/rezidencebilylev/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(249): Illuminate\Console\Application->call('queue:restart', Object(October\Rain\Support\Collection), NULL)
#5 /data/web/virtuals/166926/virtual/www/subdom/rezidencebilylev/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(221): Illuminate\Foundation\Console\Kernel->call('queue:restart')
#6 /data/web/virtuals/166926/virtual/www/subdom/rezidencebilylev/modules/system/behaviors/SettingsModel.php(207): Illuminate\Support\Facades\Facade::__callStatic('call', Array)
#7 [internal function]: System\Behaviors\SettingsModel->afterModelSave()
#8 /data/web/virtuals/166926/virtual/www/subdom/rezidencebilylev/vendor/october/rain/src/Support/Traits/Emitter.php(135): call_user_func_array(Array, Array)
#9 /data/web/virtuals/166926/virtual/www/subdom/rezidencebilylev/vendor/october/rain/src/Database/Model.php(165): October\Rain\Database\Model->fireEvent('model.afterSave')
#10 [internal function]: October\Rain\Database\Model->October\Rain\Database\{closure}(Object(System\Models\LogSetting))
#11 /data/web/virtuals/166926/virtual/www/subdom/rezidencebilylev/vendor/october/rain/src/Events/Dispatcher.php(233): call_user_func_array(Object(Closure), Array)
#12 /data/web/virtuals/166926/virtual/www/subdom/rezidencebilylev/vendor/october/rain/src/Events/Dispatcher.php(197): October\Rain\Events\Dispatcher->dispatch('eloquent.saved:...', Array, false)
#13 /data/web/virtuals/166926/virtual/www/subdom/rezidencebilylev/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Concerns/HasEvents.php(148): October\Rain\Events\Dispatcher->fire('eloquent.saved:...', Object(System\Models\LogSetting))
#14 /data/web/virtuals/166926/virtual/www/subdom/rezidencebilylev/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(576): Illuminate\Database\Eloquent\Model->fireModelEvent('saved', false)
#15 /data/web/virtuals/166926/virtual/www/subdom/rezidencebilylev/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(547): Illuminate\Database\Eloquent\Model->finishSave(Array)
#16 /data/web/virtuals/166926/virtual/www/subdom/rezidencebilylev/vendor/october/rain/src/Database/Model.php(529): Illuminate\Database\Eloquent\Model->save(Array)
#17 /data/web/virtuals/166926/virtual/www/subdom/rezidencebilylev/vendor/october/rain/src/Database/Model.php(562): October\Rain\Database\Model->saveInternal(Array)
#18 /data/web/virtuals/166926/virtual/www/subdom/rezidencebilylev/modules/system/controllers/Settings.php(104): October\Rain\Database\Model->save(NULL, 'hSUdg2ryUhdOv28...')
#19 [internal function]: System\Controllers\Settings->update_onSave('october', 'system', 'log_settings')
#20 /data/web/virtuals/166926/virtual/www/subdom/rezidencebilylev/modules/backend/classes/Controller.php(528): call_user_func_array(Array, Array)
#21 /data/web/virtuals/166926/virtual/www/subdom/rezidencebilylev/modules/backend/classes/Controller.php(419): Backend\Classes\Controller->runAjaxHandler('onSave')
#22 /data/web/virtuals/166926/virtual/www/subdom/rezidencebilylev/modules/backend/classes/Controller.php(229): Backend\Classes\Controller->execAjaxHandlers()
#23 /data/web/virtuals/166926/virtual/www/subdom/rezidencebilylev/modules/backend/classes/BackendController.php(95): Backend\Classes\Controller->run('update', Array)
#24 [internal function]: Backend\Classes\BackendController->run('system/settings...')
#25 /data/web/virtuals/166926/virtual/www/subdom/rezidencebilylev/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): call_user_func_array(Array, Array)
#26 /data/web/virtuals/166926/virtual/www/subdom/rezidencebilylev/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(45): Illuminate\Routing\Controller->callAction('run', Array)
#27 /data/web/virtuals/166926/virtual/www/subdom/rezidencebilylev/vendor/laravel/framework/src/Illuminate/Routing/Route.php(212): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(Backend\Classes\BackendController), 'run')
#28 /data/web/virtuals/166926/virtual/www/subdom/rezidencebilylev/vendor/laravel/framework/src/Illuminate/Routing/Route.php(169): Illuminate\Routing\Route->runController()
#29 /data/web/virtuals/166926/virtual/www/subdom/rezidencebilylev/vendor/laravel/framework/src/Illuminate/Routing/Router.php(658): Illuminate\Routing\Route->run()
#30 /data/web/virtuals/166926/virtual/www/subdom/rezidencebilylev/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(30): Illuminate\Routing\Router->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#31 /data/web/virtuals/166926/virtual/www/subdom/rezidencebilylev/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(41): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#32 /data/web/virtuals/166926/virtual/www/subdom/rezidencebilylev/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\Routing\Middleware\SubstituteBindings->handle(Object(Illuminate\Http\Request), Object(Closure))
#33 /data/web/virtuals/166926/virtual/www/subdom/rezidencebilylev/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#34 /data/web/virtuals/166926/virtual/www/subdom/rezidencebilylev/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#35 /data/web/virtuals/166926/virtual/www/subdom/rezidencebilylev/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\View\Middleware\ShareErrorsFromSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#36 /data/web/virtuals/166926/virtual/www/subdom/rezidencebilylev/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#37 /data/web/virtuals/166926/virtual/www/subdom/rezidencebilylev/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(63): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#38 /data/web/virtuals/166926/virtual/www/subdom/rezidencebilylev/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\Session\Middleware\StartSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#39 /data/web/virtuals/166926/virtual/www/subdom/rezidencebilylev/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#40 /data/web/virtuals/166926/virtual/www/subdom/rezidencebilylev/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#41 /data/web/virtuals/166926/virtual/www/subdom/rezidencebilylev/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse->handle(Object(Illuminate\Http\Request), Object(Closure))
#42 /data/web/virtuals/166926/virtual/www/subdom/rezidencebilylev/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#43 /data/web/virtuals/166926/virtual/www/subdom/rezidencebilylev/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(59): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#44 /data/web/virtuals/166926/virtual/www/subdom/rezidencebilylev/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\Cookie\Middleware\EncryptCookies->handle(Object(Illuminate\Http\Request), Object(Closure))
#45 /data/web/virtuals/166926/virtual/www/subdom/rezidencebilylev/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#46 /data/web/virtuals/166926/virtual/www/subdom/rezidencebilylev/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(102): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#47 /data/web/virtuals/166926/virtual/www/subdom/rezidencebilylev/vendor/laravel/framework/src/Illuminate/Routing/Router.php(660): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#48 /data/web/virtuals/166926/virtual/www/subdom/rezidencebilylev/vendor/laravel/framework/src/Illuminate/Routing/Router.php(635): Illuminate\Routing\Router->runRouteWithinStack(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request))
#49 /data/web/virtuals/166926/virtual/www/subdom/rezidencebilylev/vendor/laravel/framework/src/Illuminate/Routing/Router.php(601): Illuminate\Routing\Router->runRoute(Object(Illuminate\Http\Request), Object(Illuminate\Routing\Route))
#50 /data/web/virtuals/166926/virtual/www/subdom/rezidencebilylev/vendor/october/rain/src/Router/CoreRouter.php(20): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#51 /data/web/virtuals/166926/virtual/www/subdom/rezidencebilylev/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(176): October\Rain\Router\CoreRouter->dispatch(Object(Illuminate\Http\Request))
#52 /data/web/virtuals/166926/virtual/www/subdom/rezidencebilylev/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(30): Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}(Object(Illuminate\Http\Request))
#53 /data/web/virtuals/166926/virtual/www/subdom/rezidencebilylev/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(46): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#54 /data/web/virtuals/166926/virtual/www/subdom/rezidencebilylev/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle(Object(Illuminate\Http\Request), Object(Closure))
#55 /data/web/virtuals/166926/virtual/www/subdom/rezidencebilylev/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#56 /data/web/virtuals/166926/virtual/www/subdom/rezidencebilylev/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(102): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#57 /data/web/virtuals/166926/virtual/www/subdom/rezidencebilylev/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(151): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#58 /data/web/virtuals/166926/virtual/www/subdom/rezidencebilylev/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(116): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#59 /data/web/virtuals/166926/virtual/www/subdom/rezidencebilylev/index.php(43): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#60 {main}
````

**Comment by LukeTowers** [comment]
`php artisan queue:restart` is called when saving models that implement the SettingsModel because the queue works off of the settings data that was in the database when the queue was started. Thus, for any setting that affects the running of the queue, the queue worker needs to be restarted on updating of that setting for the changes to take effect.

I do think that the current method of doing it by default for every single backend setting is ridiculous though, perhaps you could suggest a better method; maybe a flag property on models implementing the trait to trigger the auto restart? @daftspunk any thoughts on this?

**Comment by jan-vince** [comment]
But October will be still dependend on ````putenv()```` calls, isn't it?

I was fine with version 430 so some changes between 430 and 431 introduced this problem.

Will try to dig deeper...

**Comment by jan-vince** [comment]
Hi @LukeTowers,

would you agree to update ````afterModelSave()```` method with ````try...catch```` block like this:

````
    public function afterModelSave()
    {
        Cache::forget($this->getCacheKey());

        try {
            Artisan::call('queue:restart');
        } catch(\Exception $e) {
            Log::warning($e->getMessage());
        }
    }
````

This would have zero impact on systems with ````putenv()```` enabled but allow installations on limited hostings to be able to save settings that implement ````SettingsModel````.

**Comment by LukeTowers** [comment]
That's probably a good solution in general, but since we're looking at this anyways I'd like a better solution than always restarting the queue driver on every settingsmodel save.

**Comment by jan-vince** [comment]
Hi @LukeTowers 

I have created PR #3342 and added a video so you can check, what is fixed and how it works with ````try...catch```` block.

Would be great if you can merge it and add to a next October version.

*To solve a problem with ````queue:restart```` (with every SettingsModel save) is beyond my skills right now. Maybe @daftspunk or @jimcottrell can help here.*

**Comment by LukeTowers** [comment]
Merged it @jan-vince, thanks! I'd still like a better solution, but this will work for now.

**Comment by jimcottrell** [comment]
@LukeTowers I disagree that it's ridiculous to restart the queue on any settings change, as settings don't change that often, it's not a giant performance hit, and to me it seems like more work than it's worth to have to decide what settings impact queue workers, possibly forgetting to change flags when settings are added/changed and then having to debug why your system isn't doing what you think it should. Why shouldn't we just guarantee that queue workers are always seeing the latest settings? And if you're ever going to restart the queue automatically (even with only flagged settings) or make any other Artisan call, it sounds like if your host disables `putenv` you're still out of luck. It's not restarting the queue that's the problem.

The Artisan call just updates a cache value, but it's the only place that functionality is exposed, so although yes, we can remove the Artisan call, it would mean that if Laravel changes anything about how to restart queue workers (different cache key, etc.), October would also have to be updated. It's not a huge thing, but it was an attempt to avoid needless duplication. Perhaps this should be an upstream issue for Laravel/Symfony not to depend on `putenv` for console, or for Laravel to move the actual queue restart out of a console command so we can call the same code the console command does without actually using the console command.

**Comment by LukeTowers** [comment]
Fair enough @jimcottrell, those are reasonable points to make. Ideally the issue would be resolved upstream with Laravel, not sure what the best solution on that end would be though

**Comment by jan-vince** [comment]
Right now the original problem with Exception is solved so I will close this.
