### ISSUE TITLE
Error stream_set_blocking() on sending email

### ISSUE THREAD

**Issue by mattiak14** [octobercms/october#3423]
##### Expected behavior
ErrorException: stream_set_blocking() expects parameter 1 to be resource, null given in /data/web/e77577/html/backend14/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/StreamBuffer.php:271
Stack trace:
```
#0 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(2, 'stream_set_bloc...', '/data/web/e7757...', 271, Array)
#1 /data/web/e77577/html/backend14/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/StreamBuffer.php(271): stream_set_blocking(NULL, 1)
#2 /data/web/e77577/html/backend14/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/StreamBuffer.php(58): Swift_Transport_StreamBuffer->establishSocketConnection()
#3 /data/web/e77577/html/backend14/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/AbstractSmtpTransport.php(137): Swift_Transport_StreamBuffer->initialize(Array)
#4 /data/web/e77577/html/backend14/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Mailer.php(64): Swift_Transport_AbstractSmtpTransport->start()
#5 /data/web/e77577/html/backend14/vendor/laravel/framework/src/Illuminate/Mail/Mailer.php(451): Swift_Mailer->send(Object(Swift_Message), Array)
#6 /data/web/e77577/html/backend14/vendor/october/rain/src/Mail/Mailer.php(84): Illuminate\Mail\Mailer->sendSwiftMessage(Object(Swift_Message))
#7 /data/web/e77577/html/backend14/vendor/october/rain/src/Mail/Mailer.php(136): October\Rain\Mail\Mailer->send('martin.forms::m...', Array, Object(Closure))
#8 /data/web/e77577/html/backend14/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(221): October\Rain\Mail\Mailer->sendTo(Array, 'martin.forms::m...', Array, Object(Closure))
#9 /data/web/e77577/html/backend14/plugins/martin/forms/classes/SendMail.php(57): Illuminate\Support\Facades\Facade::__callStatic('sendTo', Array)
#10 /data/web/e77577/html/backend14/plugins/martin/forms/classes/MagicForm.php(186): Martin\Forms\Classes\SendMail::sendNotification(Array, Array, Object(Martin\Forms\Models\Record), Object(October\Rain\Database\Collection))
#11 /data/web/e77577/html/backend14/modules/cms/classes/ComponentBase.php(163): Martin\Forms\Classes\MagicForm->onFormSubmit()
#12 /data/web/e77577/html/backend14/modules/cms/classes/Controller.php(702): Cms\Classes\ComponentBase->runAjaxHandler('onFormSubmit')
#13 /data/web/e77577/html/backend14/modules/cms/classes/Controller.php(625): Cms\Classes\Controller->runAjaxHandler('odtform::onForm...')
#14 /data/web/e77577/html/backend14/modules/cms/classes/Controller.php(330): Cms\Classes\Controller->execAjaxHandlers()
#15 /data/web/e77577/html/backend14/modules/cms/classes/Controller.php(213): Cms\Classes\Controller->runPage(Object(Cms\Classes\Page))
#16 /data/web/e77577/html/backend14/modules/cms/classes/CmsController.php(50): Cms\Classes\Controller->run('contatto-aziend...')
#17 [internal function]: Cms\Classes\CmsController->run('contatto-aziend...')
#18 /data/web/e77577/html/backend14/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): call_user_func_array(Array, Array)
#19 /data/web/e77577/html/backend14/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(45): Illuminate\Routing\Controller->callAction('run', Array)
#20 /data/web/e77577/html/backend14/vendor/laravel/framework/src/Illuminate/Routing/Route.php(212): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(Cms\Classes\CmsController), 'run')
#21 /data/web/e77577/html/backend14/vendor/laravel/framework/src/Illuminate/Routing/Route.php(169): Illuminate\Routing\Route->runController()
#22 /data/web/e77577/html/backend14/vendor/laravel/framework/src/Illuminate/Routing/Router.php(658): Illuminate\Routing\Route->run()
#23 /data/web/e77577/html/backend14/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(30): Illuminate\Routing\Router->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#24 /data/web/e77577/html/backend14/plugins/rainlab/translate/classes/LocaleMiddleware.php(29): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#25 /data/web/e77577/html/backend14/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): RainLab\Translate\Classes\LocaleMiddleware->handle(Object(Illuminate\Http\Request), Object(Closure))
#26 /data/web/e77577/html/backend14/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#27 /data/web/e77577/html/backend14/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(41): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#28 /data/web/e77577/html/backend14/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\Routing\Middleware\SubstituteBindings->handle(Object(Illuminate\Http\Request), Object(Closure))
#29 /data/web/e77577/html/backend14/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#30 /data/web/e77577/html/backend14/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#31 /data/web/e77577/html/backend14/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\View\Middleware\ShareErrorsFromSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#32 /data/web/e77577/html/backend14/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#33 /data/web/e77577/html/backend14/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(63): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#34 /data/web/e77577/html/backend14/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\Session\Middleware\StartSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#35 /data/web/e77577/html/backend14/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#36 /data/web/e77577/html/backend14/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#37 /data/web/e77577/html/backend14/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse->handle(Object(Illuminate\Http\Request), Object(Closure))
#38 /data/web/e77577/html/backend14/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#39 /data/web/e77577/html/backend14/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(59): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#40 /data/web/e77577/html/backend14/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\Cookie\Middleware\EncryptCookies->handle(Object(Illuminate\Http\Request), Object(Closure))
#41 /data/web/e77577/html/backend14/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#42 /data/web/e77577/html/backend14/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(102): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#43 /data/web/e77577/html/backend14/vendor/laravel/framework/src/Illuminate/Routing/Router.php(660): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#44 /data/web/e77577/html/backend14/vendor/laravel/framework/src/Illuminate/Routing/Router.php(635): Illuminate\Routing\Router->runRouteWithinStack(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request))
#45 /data/web/e77577/html/backend14/vendor/laravel/framework/src/Illuminate/Routing/Router.php(601): Illuminate\Routing\Router->runRoute(Object(Illuminate\Http\Request), Object(Illuminate\Routing\Route))
#46 /data/web/e77577/html/backend14/vendor/october/rain/src/Router/CoreRouter.php(20): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#47 /data/web/e77577/html/backend14/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(176): October\Rain\Router\CoreRouter->dispatch(Object(Illuminate\Http\Request))
#48 /data/web/e77577/html/backend14/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(30): Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}(Object(Illuminate\Http\Request))
#49 /data/web/e77577/html/backend14/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(46): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#50 /data/web/e77577/html/backend14/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle(Object(Illuminate\Http\Request), Object(Closure))
#51 /data/web/e77577/html/backend14/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#52 /data/web/e77577/html/backend14/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(102): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#53 /data/web/e77577/html/backend14/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(151): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#54 /data/web/e77577/html/backend14/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(116): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#55 /data/web/e77577/html/backend14/index.php(43): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#56 {main}
```
##### Reproduce steps
initially I could send without errors
It started when I upgraded to the latest version of octobercms that forced me to upgrade to php 7
the error occurs on any frontend / backend email sending
sending email is configured in smtp mode but also varying the mode I always get error
thanks

##### October build
current build 434

**Comment by LukeTowers** [comment]
Some googling around reveals that you need to make sure that `proc_open()` is enabled on your hosting environment. See https://stackoverflow.com/questions/36115345/laravel-5-1-sending-email-error-stream-set-blocking-expects-parameter-1-to-b#comment65950282_36115345 and http://www.devnetwork.net/viewtopic.php?f=52&t=138845.

As a related question, would managed OctoberCMS hosting be a service that you would be interested in?
