### ISSUE TITLE
Package files from server are corrupt

### ISSUE THREAD

**Issue by MattHamer5** [octobercms/october#3968]
##### Actual behavior
Currently using Vagrant ScotchBox. Trying to install October using the wizard (install.php), I go through all the steps successfully; link my MySQL Database and Create an Account. When it comes to the actual installation page it immediately says

> Package files from server are corrupt

##### Error Logs:
`[2018/12/07 03:54:08] Install step: downloadCore`
`[2018/12/07 03:54:11] File hash mismatch: f4018fccd269a1ddcedc4a0e0c13d3d9 (expected) vs 7ddfba6720ad770cbacf1571f8c1f0a0 (actual)`
`[2018/12/07 03:54:11] Local file size: 10982423`
`[2018/12/07 03:54:11] Handler error (onInstallStep): Package files from server are corrupt`
`[2018/12/07 03:54:11] Trace log:`
`#0 /var/www/public/install_files/php/Installer.php(312): Installer->requestServerFile('core', 'f4018fccd269a1d...', 'core/get', Array)`
`#1 /var/www/public/install_files/php/Installer.php(48): Installer->onInstallStep()`
`#2 /var/www/public/install_files/php/boot.php(91): Installer->__construct()`
`#3 /var/www/public/install.php(1): include('/var/www/public...')`
`#4 {main}`

##### October build
latest

**Comment by MattHamer5** [comment]
I got this setup and working straight away when I switched over to Homestead, so unsure if it was just a ScotchBox problem.
