### ISSUE TITLE
installer bug (mysql)

### ISSUE THREAD

**Issue by PowerChaos** [octobercms/october#4146]
well the logs just says it all

or in short , it seems it does not store the correct informtion in the database.php file
even if i manual adjust it then i get the error that the tables are not found

i tried the latest version

Greets From PowerChaos
```
.============================ POST REQUEST ==========================.
[2019/02/18 02:31:00] Postback payload: Array
(
    [step] => setupConfig
    [meta] => Array
        (
            [core] => Array
                (
                    [hash] => d1028fbd034b2639b0d2ca0869002836
                    [build] => 446
                    [uhash] => b4b79ec07b137e6c84605ac76f616781
                )

            [plugins] => Array
                (
                    [RainLab.User] => 57b0b68011e2fb5bd8fca8b996732c33
                    [RainLab.Translate] => e7cad425c474f9a845ad979a9e0b6473
                    [RainLab.Pages] => bdcab1539199022a17ea88ef0923fb8f
                    [RainLab.UserPlus] => fc08a9398e8f59bc3bf48add0cc91dbc
                    [RainLab.Location] => b8267852963930295fa97a0b883a968e
                    [OFFLINE.SiteSearch] => a3e2303b45d632d43aac93915adbf442
                    [Responsiv.Currency] => bd91e4c16db6d36c9861af90ca4026b4
                    [Responsiv.Pay] => 584b32745ced9f4d3948c76c3e61e2b7
                    [JanVince.SmallExtensions] => a8704bed787014586f6accff6f4aeb24
                    [LukeTowers.SnappyPDF] => 9fc09905f0bf0efa7e191a5d81cac8ae
                    [JanVince.SmallContactForm] => 09fc8dc2fc05971ed4db9ad8913620a6
                    [RainLab.Notify] => d8366e24dc7060ea375cc6b81c08f4b9
                    [JanVince.SmallRecords] => 74ff9af7f51f48ad803240cd82737de7
                    [Initbiz.CumulusCore] => 10f647e555142615518cad3c1c4e281e
                    [Inetis.RicheditorSnippets] => 5e60635bbaab7f0e8f16a3d8fe1acbca
                    [Initbiz.Money] => f4fd8b0c071e71b24dc6c0fadfa3dd9b
                    [OFFLINE.Mall] => 0079fdb10bbd480fb2743d688482f5f9
                    [Initbiz.InitDry] => 5236aecb0ff473687b992ccd306d024f
                    [Briddle.Pay] => 91d46c38ac99f591b6df0c2a3d17c673
                )

            [themes] => Array
                (
                    [JanVince.smalltheme-3] => fe8894fb70d08cc41f5bdb42667361cf
                    [OFFLINE.oc-mall-theme] => 3f6866af519fa9f4a57d4004bf37e0f3
                )

        )

    [db_type] => mysql
    [db_host] => localhost
    [db_port] => 
    [db_name] => pc_october
    [db_user] => pc_october
    [db_pass] => *******
    [admin_first_name] => Admin
    [admin_last_name] => Person
    [admin_email] => *******@*****.com
    [admin_login] => PowerChaos
    [admin_password] => *******
    [admin_confirm_password] => *******
    [backend_uri] => /backend
    [encryption_code] => *******
    [file_mask] => 664
    [folder_mask] => 755
    [handler] => onInstallStep
)

[2019/02/18 02:31:00] Install step: setupConfig
[2019/02/18 01:31:00] Handler error (onInstallStep): SQLSTATE[HY000] [1045] Access denied for user 'root'@'localhost' (using password: NO) (SQL: select * from information_schema.tables where table_schema = database and table_name = offline_mall_notifications)
[2019/02/18 01:31:00] Trace log:
#0 /home/pc/public_html/vendor/laravel/framework/src/Illuminate/Database/Connection.php(624): Illuminate\Database\Connection->runQueryCallback('select * from i...', Array, Object(Closure))
#1 /home/pc/public_html/vendor/laravel/framework/src/Illuminate/Database/Connection.php(333): Illuminate\Database\Connection->run('select * from i...', Array, Object(Closure))
#2 /home/pc/public_html/vendor/laravel/framework/src/Illuminate/Database/Schema/MySqlBuilder.php(18): Illuminate\Database\Connection->select('select * from i...', Array)
#3 /home/pc/public_html/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(221): Illuminate\Database\Schema\MySqlBuilder->hasTable('offline_mall_no...')
#4 /home/pc/public_html/plugins/offline/mall/models/Notification.php(34): Illuminate\Support\Facades\Facade::__callStatic('hasTable', Array)
#5 /home/pc/public_html/plugins/offline/mall/classes/events/MailingEventHandler.php(20): OFFLINE\Mall\Models\Notification::getEnabled()
#6 [internal function]: OFFLINE\Mall\Classes\Events\MailingEventHandler->__construct()
#7 /home/pc/public_html/vendor/laravel/framework/src/Illuminate/Container/Container.php(785): ReflectionClass->newInstanceArgs(Array)
#8 /home/pc/public_html/vendor/laravel/framework/src/Illuminate/Container/Container.php(631): Illuminate\Container\Container->build('OFFLINE\\Mall\\Cl...')
#9 /home/pc/public_html/vendor/laravel/framework/src/Illuminate/Container/Container.php(586): Illuminate\Container\Container->resolve('OFFLINE\\Mall\\Cl...', Array)
#10 /home/pc/public_html/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(732): Illuminate\Container\Container->make('OFFLINE\\Mall\\Cl...', Array)
#11 /home/pc/public_html/vendor/october/rain/src/Foundation/Application.php(162): Illuminate\Foundation\Application->make('OFFLINE\\Mall\\Cl...')
#12 /home/pc/public_html/vendor/laravel/framework/src/Illuminate/Container/Container.php(256): October\Rain\Foundation\Application->make('OFFLINE\\Mall\\Cl...', Array)
#13 /home/pc/public_html/vendor/laravel/framework/src/Illuminate/Container/Container.php(749): Illuminate\Container\Container->Illuminate\Container\{closure}(Object(October\Rain\Foundation\Application), Array)
#14 /home/pc/public_html/vendor/laravel/framework/src/Illuminate/Container/Container.php(631): Illuminate\Container\Container->build(Object(Closure))
#15 /home/pc/public_html/vendor/laravel/framework/src/Illuminate/Container/Container.php(586): Illuminate\Container\Container->resolve('MailingEventHan...', Array)
#16 /home/pc/public_html/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(732): Illuminate\Container\Container->make('MailingEventHan...', Array)
#17 /home/pc/public_html/vendor/october/rain/src/Foundation/Application.php(162): Illuminate\Foundation\Application->make('MailingEventHan...')
#18 /home/pc/public_html/vendor/october/rain/src/Events/Dispatcher.php(148): October\Rain\Foundation\Application->make('MailingEventHan...')
#19 /home/pc/public_html/vendor/october/rain/src/Events/Dispatcher.php(134): October\Rain\Events\Dispatcher->resolveSubscriber('MailingEventHan...')
#20 /home/pc/public_html/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(221): October\Rain\Events\Dispatcher->subscribe('MailingEventHan...')
#21 /home/pc/public_html/plugins/offline/mall/classes/registration/BootEvents.php(40): Illuminate\Support\Facades\Facade::__callStatic('subscribe', Array)
#22 /home/pc/public_html/plugins/offline/mall/classes/registration/BootEvents.php(23): OFFLINE\Mall\Plugin->registerGenericEvents()
#23 /home/pc/public_html/plugins/offline/mall/Plugin.php(39): OFFLINE\Mall\Plugin->registerEvents()
#24 /home/pc/public_html/modules/system/classes/PluginManager.php(293): OFFLINE\Mall\Plugin->boot()
#25 /home/pc/public_html/modules/system/classes/PluginManager.php(275): System\Classes\PluginManager->bootPlugin(Object(OFFLINE\Mall\Plugin))
#26 /home/pc/public_html/modules/system/ServiceProvider.php(93): System\Classes\PluginManager->bootAll()
#27 [internal function]: System\ServiceProvider->boot()
#28 /home/pc/public_html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(29): call_user_func_array(Array, Array)
#29 /home/pc/public_html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(87): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#30 /home/pc/public_html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(31): Illuminate\Container\BoundMethod::callBoundMethod(Object(October\Rain\Foundation\Application), Array, Object(Closure))
#31 /home/pc/public_html/vendor/laravel/framework/src/Illuminate/Container/Container.php(549): Illuminate\Container\BoundMethod::call(Object(October\Rain\Foundation\Application), Array, Array, NULL)
#32 /home/pc/public_html/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(792): Illuminate\Container\Container->call(Array)
#33 /home/pc/public_html/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(775): Illuminate\Foundation\Application->bootProvider(Object(System\ServiceProvider))
#34 [internal function]: Illuminate\Foundation\Application->Illuminate\Foundation\{closure}(Object(System\ServiceProvider), 23)
#35 /home/pc/public_html/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(776): array_walk(Array, Object(Closure))
#36 /home/pc/public_html/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/BootProviders.php(17): Illuminate\Foundation\Application->boot()
#37 /home/pc/public_html/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(213): Illuminate\Foundation\Bootstrap\BootProviders->bootstrap(Object(October\Rain\Foundation\Application))
#38 /home/pc/public_html/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(296): Illuminate\Foundation\Application->bootstrapWith(Array)
#39 /home/pc/public_html/install_files/php/Installer.php(677): Illuminate\Foundation\Console\Kernel->bootstrap()
#40 /home/pc/public_html/install_files/php/Installer.php(408): Installer->bootFramework()
#41 /home/pc/public_html/install_files/php/Installer.php(378): Installer->buildConfigFile()
#42 /home/pc/public_html/install_files/php/Installer.php(48): Installer->onInstallStep()
#43 /home/pc/public_html/install_files/php/boot.php(91): Installer->__construct()
#44 /home/pc/public_html/install.php(1): include('/home/pc/public...')
#45 {main}
```

**Comment by PowerChaos** [comment]
update::

after using the artisian comand to install it then the files and db is succesfully created
but then it trows out a warning that the log files could not be found

after manual creating that file , does it seems it works

or it is my server settings that are not playing nice with this script , or the script does not play nice in general ?

Greets from PowerChaos

**Comment by w20k** [comment]
@PowerChaos pretty sure it doesn't play well with your server.

This error normally means that either the password you are using doesn't match, or the user doesn't exist.
```
SQLSTATE[HY000] [1045] Access denied for user 'root'@'localhost' (using password: NO) (SQL: select * from information_schema.tables where table_schema = database and table_name = offline_mall_notifications)
```

Side note: From my exp. composer does a better job.

**Comment by PowerChaos** [comment]
@w20k 
it seems indeed that my server is doing this ( atleast for octobercms , other installers are just fine ) 
after i manual assign the public_html folder to 777 permission i was able to install plugins

the error you see above means that the config file does not take over my settings i filled to the installer
so the installer does not check if the db connection is succesfull or can even write the config file ... 
even when the pre check says that everything is writable ??

to make things even more fun

so the online installer start the install up to a point that it installs my plugins fromt he project ( after download ) and trows that sql error

in ssh , i use the artisian command and that works just fine until i go to the website url
where it trows the log write error ( because file does not exist , manual created it ) 
then after i attached my project link , it start trowing a unzip error ( but files are donwloaded correctly  )

so now i changed the chmod of the full public html to 777 ( full public acces ... love those ) 
and so far it seems working now

so instead of a bug report will this be more a suggestion now
can they fix file permission checks ? so others can also enjoy this nice script ?
as it took me some debug to figure out 
Greets From PowerChaos

**Comment by w20k** [comment]
@PowerChaos I think it's not well documented (PRs to docs are welcomed, https://octobercms.com/docs/setup/installation#wizard-installation), but you should be fine with `Step 5` in this tutorial.

`Step 5: Download OctoberCMS Latest Release`
Particularly, this one:
```
sudo chown -R www-data:www-data /var/www/html/octobercms/
sudo chmod -R 755 /var/www/html/octobercms/
```
https://websiteforstudents.com/install-octobercms-on-ubuntu-16-04-lts-with-apache2-mariadb-and-php-7-1-support/

**Comment by PowerChaos** [comment]
thank you @w20k 
but i run centos and cpanel 🔋 
easyapache 4 ( apache 2.4 ) with php-fpm and php 7.2 - 7.1 - 5.6
and some more stuff configured that could provide a conflict at some cases

but i do wonder why this specific script create everything as root when others does it as the user like it need to be

some settings prevent execution by differend owners , and as all users run as there own account should nothing be created as root ( or nobody ) 

sometimes it happends with other scripts ( like upload scripts ) that i need to reset the rights back to the account user after install 
but with this cms i needed to this already a couple times ( plugin installs seems to mess up dir permission ? )

it seems this script somehow change the ownership of the folders or reset a chmod back to the default

i do love the script , but it would also be nice if this can be investigated to make installs a bit less complicated then it is for me at this moment

as it shoulnd happen that i need to disable some security settings or need to use ssh (or put my folder on 777 when 755 and 644 also got write acces  as owner) to get the cms working

Thank you for your time and support
Greets From PowerChaos

**Comment by w20k** [comment]
@PowerChaos hm...I might give it a try on my server. To test it out. 
Will let you know if I'd find something useful.

**Comment by bennothommo** [comment]
Closing as it has been over a month since any activity on this occurred and we are trying to figure out what issues are still relevant. If this is still something that you would like to see through to fruition please respond and we can get the ball rolling.
