### ISSUE TITLE
Datafeed not working on Postgres 9.6

### ISSUE THREAD

**Issue by dimensi** [octobercms/october#4249]
- OctoberCMS Build: 
- PHP Version: 7.2
- Database Engine: Postgres 9.6
- Plugins Installed: Builder

### Description:
Then i try to use DataFeed, i got error.
```
Next Illuminate\Database\QueryException: SQLSTATE[XX000]: Internal error: 7 ERROR:  failed to find conversion function from unknown to text (SQL: select id as id, (SELECT 'post') as tag_name, (SELECT dh_content_posts.id) as order_by_column_name from "dh_content_posts" where "published" = 1 union all select id as id, (SELECT 'pubs') as tag_name, (SELECT dh_content_publications.id) as order_by_column_name from "dh_content_publications" where "published" = 1 order by "order_by_column_name" desc) in /var/www/html/app/vendor/laravel/framework/src/Illuminate/Database/Connection.php:664
Stack trace:
#0 /var/www/html/app/vendor/laravel/framework/src/Illuminate/Database/Connection.php(624): Illuminate\Database\Connection->runQueryCallback('select id as id...', Array, Object(Closure))
#1 /var/www/html/app/vendor/laravel/framework/src/Illuminate/Database/Connection.php(333): Illuminate\Database\Connection->run('select id as id...', Array, Object(Closure))
#2 /var/www/html/app/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(1719): Illuminate\Database\Connection->select('select id as id...', Array, true)
#3 /var/www/html/app/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(1704): Illuminate\Database\Query\Builder->runSelect()
#4 /var/www/html/app/vendor/october/rain/src/Database/QueryBuilder.php(122): Illuminate\Database\Query\Builder->get(Array)
#5 /var/www/html/app/vendor/october/rain/src/Database/QueryBuilder.php(92): October\Rain\Database\QueryBuilder->getDuplicateCached(Array)
#6 /var/www/html/app/vendor/october/rain/src/Database/DataFeed.php(117): October\Rain\Database\QueryBuilder->get()
#7 /var/www/html/app/plugins/digitalhorizon/content/routes.php(17): October\Rain\Database\DataFeed->get()
#8 /var/www/html/app/vendor/laravel/framework/src/Illuminate/Routing/Route.php(198): System\Classes\PluginManager->{closure}()
#9 /var/www/html/app/vendor/laravel/framework/src/Illuminate/Routing/Route.php(172): Illuminate\Routing\Route->runCallable()
#10 /var/www/html/app/vendor/laravel/framework/src/Illuminate/Routing/Router.php(658): Illuminate\Routing\Route->run()
#11 /var/www/html/app/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(30): Illuminate\Routing\Router->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#12 /var/www/html/app/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(102): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#13 /var/www/html/app/vendor/laravel/framework/src/Illuminate/Routing/Router.php(660): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#14 /var/www/html/app/vendor/laravel/framework/src/Illuminate/Routing/Router.php(635): Illuminate\Routing\Router->runRouteWithinStack(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request))
#15 /var/www/html/app/vendor/laravel/framework/src/Illuminate/Routing/Router.php(601): Illuminate\Routing\Router->runRoute(Object(Illuminate\Http\Request), Object(Illuminate\Routing\Route))
#16 /var/www/html/app/vendor/october/rain/src/Router/CoreRouter.php(20): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#17 /var/www/html/app/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(176): October\Rain\Router\CoreRouter->dispatch(Object(Illuminate\Http\Request))
#18 /var/www/html/app/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(30): Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}(Object(Illuminate\Http\Request))
#19 /var/www/html/app/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(46): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#20 /var/www/html/app/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle(Object(Illuminate\Http\Request), Object(Closure))
#21 /var/www/html/app/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#22 /var/www/html/app/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(102): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#23 /var/www/html/app/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(151): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#24 /var/www/html/app/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(116): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#25 /var/www/html/app/index.php(43): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#26 {main}  
```

### Steps To Reproduce:

```php
  Route::get('feed', function () {
    $feed = new DataFeed;
    $feed->add('post', Post::where('published', true));
    $feed->add('pubs', Publication::where('published', true));
    return $feed->get();
  });
```

**Comment by dimensi** [comment]
https://stackoverflow.com/questions/18073901/failed-to-find-conversion-function-from-unknown-to-text
It says here that postgres just can't do that

**Comment by dimensi** [comment]
After debug and little research i found a answer. 
Need to cast tag_type to text.

**Comment by bennothommo** [comment]
Fixed by https://github.com/octobercms/library/pull/403.
