### ISSUE TITLE
FieldParser Error: Maximum function nesting level of '1000' reached, aborting!

### ISSUE THREAD

**Issue by grahambrown11** [octobercms/october#4709]
- OctoberCMS Build: 458
- PHP Version: 7.1.20
- Database Engine: MySQL
- Plugins Installed
    - Responsiv.Campaign Manager-1.2.1

### Description:
```
Symfony\Component\Debug\Exception\FatalThrowableError: Maximum function nesting level of '1000' reached, aborting! in /vagrant/october-mailer/web/vendor/laravel/framework/src/Illuminate/Support/Arr.php:21
Stack trace:
#0 /vagrant/october-mailer/web/vendor/laravel/framework/src/Illuminate/Support/Arr.php(21): is_array(Array)
#1 /vagrant/october-mailer/web/vendor/laravel/framework/src/Illuminate/Support/Arr.php(280): Illuminate\Support\Arr::accessible(Array)
#2 /vagrant/october-mailer/web/vendor/laravel/framework/src/Illuminate/Support/helpers.php(157): Illuminate\Support\Arr::get(Array, 'fields', Array)
#3 /vagrant/october-mailer/web/vendor/october/rain/src/Parse/Syntax/FieldParser.php(165): array_get(Array, 'fields', Array)
#4 /vagrant/october-mailer/web/vendor/october/rain/src/Parse/Syntax/FieldParser.php(165): October\Rain\Parse\Syntax\FieldParser->getDefaultParams(Array)
#5 /vagrant/october-mailer/web/vendor/october/rain/src/Parse/Syntax/FieldParser.php(165): October\Rain\Parse\Syntax\FieldParser->getDefaultParams(Array)
#6 /vagrant/october-mailer/web/vendor/october/rain/src/Parse/Syntax/FieldParser.php(165): October\Rain\Parse\Syntax\FieldParser->getDefaultParams(Array)
#7 /vagrant/october-mailer/web/vendor/october/rain/src/Parse/Syntax/FieldParser.php(165): October\Rain\Parse\Syntax\FieldParser->getDefaultParams(Array)
...
```
The cause is the way in which the fields is tested for validity, it would be better to use the `is_null` function

### Steps To Reproduce:
Create a repeater using external yaml config in a campaign template
`{variable name="sections" type="repeater" prompt="Add Section" groups="~/themes/mailer/sections.yaml"}`

**Comment by daftspunk** [comment]
Fixed by https://github.com/octobercms/library/pull/438
