### ISSUE TITLE
[Laravel 6] Method October\Rain\Mail\Mailer::setGlobalTo does not exist.

### ISSUE THREAD

**Issue by tobias-kuendig** [octobercms/october#4915]
Using a global "mail to" address in Laravel 6 fails. It looks like the `Illuminate\Mail\MAiler::setGlobalTo` method has been renamed to ` setGlobalToAndRemoveCcAndBcc`.

https://laravel.com/api/6.x/Illuminate/Mail/Mailer.html#method_setGlobalToAndRemoveCcAndBcc

Full stack trace:

```
[2020-01-28 10:06:20] dev.ERROR: BadMethodCallException: Method October\Rain\Mail\Mailer::setGlobalTo does not exist. in /dir/vendor/laravel/framework/src/Illuminate/Support/Traits/Macroable.php:103
Stack trace:
#0 /dir/vendor/october/rain/src/Mail/Mailer.php(81): Illuminate\Mail\Mailer->__call('setGlobalTo', Array)
#1 /dir/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(261): October\Rain\Mail\Mailer->send('offline.mall::m...', Array, Object(Closure))
#2 /dir/plugins/offline/mall/classes/jobs/SendOrderConfirmationToCustomer.php(41): Illuminate\Support\Facades\Facade::__callStatic('send', Array)
#3 /dir/vendor/laravel/framework/src/Illuminate/Queue/Jobs/Job.php(88): OFFLINE\Mall\Classes\Jobs\SendOrderConfirmationToCustomer->fire(Object(Illuminate\Queue\Jobs\SyncJob), Array)
#4 /dir/vendor/laravel/framework/src/Illuminate/Queue/SyncQueue.php(45): Illuminate\Queue\Jobs\Job->fire()
#5 /dir/vendor/laravel/framework/src/Illuminate/Queue/QueueManager.php(258): Illuminate\Queue\SyncQueue->push('OFFLINE\\Mall\\Cl...', Array)
#6 /dir/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(261): Illuminate\Queue\QueueManager->__call('push', Array)
#7 /dir/plugins/offline/mall/classes/events/MailingEventHandler.php(107): Illuminate\Support\Facades\Facade::__callStatic('push', Array)
#8 [internal function]: OFFLINE\Mall\Classes\Events\MailingEventHandler->checkoutSucceeded(Object(OFFLINE\Mall\Classes\Payments\PaymentResult))
#9 /dir/vendor/october/rain/src/Events/Dispatcher.php(353): call_user_func_array(Array, Array)
#10 [internal function]: October\Rain\Events\Dispatcher->October\Rain\Events\{closure}(Object(OFFLINE\Mall\Classes\Payments\PaymentResult))
#11 /dir/vendor/october/rain/src/Events/Dispatcher.php(233): call_user_func_array(Object(Closure), Array)
#12 /dir/vendor/october/rain/src/Events/Dispatcher.php(197): October\Rain\Events\Dispatcher->dispatch('mall.checkout.s...', Array, false)
#13 /dir/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(261): October\Rain\Events\Dispatcher->fire('mall.checkout.s...', Array)
#14 /dir/plugins/offline/mall/classes/payments/PaymentRedirector.php(106): Illuminate\Support\Facades\Facade::__callStatic('fire', Array)
#15 /dir/plugins/offline/mall/classes/payments/PaymentService.php(71): OFFLINE\Mall\Classes\Payments\PaymentRedirector->handlePaymentResult(Object(OFFLINE\Mall\Classes\Payments\PaymentResult))
#16 /dir/plugins/offline/mall/components/Checkout.php(240): OFFLINE\Mall\Classes\Payments\PaymentService->process()
#17 /dir/modules/cms/classes/ComponentBase.php(187): OFFLINE\Mall\Components\Checkout->onCheckout()
#18 /dir/modules/cms/classes/Controller.php(848): Cms\Classes\ComponentBase->runAjaxHandler('onCheckout')
#19 /dir/modules/cms/classes/Controller.php(739): Cms\Classes\Controller->runAjaxHandler('checkout::onChe...')
#20 /dir/modules/cms/classes/Controller.php(372): Cms\Classes\Controller->execAjaxHandlers()
#21 /dir/modules/cms/classes/Controller.php(223): Cms\Classes\Controller->runPage(Object(Cms\Classes\Page))
#22 /dir/modules/cms/classes/CmsController.php(50): Cms\Classes\Controller->run('checkout/confir...')
#23 [internal function]: Cms\Classes\CmsController->run('checkout/confir...')
#24 /dir/plugins/bedard/debugbar/vendor/illuminate/routing/Controller.php(54): call_user_func_array(Array, Array)
#25 /dir/plugins/bedard/debugbar/vendor/illuminate/routing/ControllerDispatcher.php(45): Illuminate\Routing\Controller->callAction('run', Array)
#26 /dir/plugins/bedard/debugbar/vendor/illuminate/routing/Route.php(219): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(Cms\Classes\CmsController), 'run')
#27 /dir/plugins/bedard/debugbar/vendor/illuminate/routing/Route.php(176): Illuminate\Routing\Route->runController()
#28 /dir/vendor/laravel/framework/src/Illuminate/Routing/Router.php(681): Illuminate\Routing\Route->run()
#29 /dir/plugins/bedard/debugbar/vendor/illuminate/pipeline/Pipeline.php(130): Illuminate\Routing\Router->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#30 /dir/plugins/rainlab/translate/classes/LocaleMiddleware.php(29): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#31 /dir/plugins/bedard/debugbar/vendor/illuminate/pipeline/Pipeline.php(171): RainLab\Translate\Classes\LocaleMiddleware->handle(Object(Illuminate\Http\Request), Object(Closure))
#32 /dir/plugins/bedard/debugbar/vendor/illuminate/routing/Middleware/SubstituteBindings.php(41): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#33 /dir/plugins/bedard/debugbar/vendor/illuminate/pipeline/Pipeline.php(171): Illuminate\Routing\Middleware\SubstituteBindings->handle(Object(Illuminate\Http\Request), Object(Closure))
#34 /dir/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#35 /dir/plugins/bedard/debugbar/vendor/illuminate/pipeline/Pipeline.php(171): Illuminate\View\Middleware\ShareErrorsFromSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#36 /dir/plugins/bedard/debugbar/vendor/illuminate/session/Middleware/StartSession.php(56): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#37 /dir/plugins/bedard/debugbar/vendor/illuminate/pipeline/Pipeline.php(171): Illuminate\Session\Middleware\StartSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#38 /dir/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#39 /dir/plugins/bedard/debugbar/vendor/illuminate/pipeline/Pipeline.php(171): Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse->handle(Object(Illuminate\Http\Request), Object(Closure))
#40 /dir/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(66): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#41 /dir/plugins/bedard/debugbar/vendor/illuminate/pipeline/Pipeline.php(171): Illuminate\Cookie\Middleware\EncryptCookies->handle(Object(Illuminate\Http\Request), Object(Closure))
#42 /dir/plugins/bedard/debugbar/vendor/illuminate/pipeline/Pipeline.php(105): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#43 /dir/vendor/laravel/framework/src/Illuminate/Routing/Router.php(683): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#44 /dir/vendor/laravel/framework/src/Illuminate/Routing/Router.php(658): Illuminate\Routing\Router->runRouteWithinStack(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request))
#45 /dir/vendor/laravel/framework/src/Illuminate/Routing/Router.php(624): Illuminate\Routing\Router->runRoute(Object(Illuminate\Http\Request), Object(Illuminate\Routing\Route))
#46 /dir/vendor/october/rain/src/Router/CoreRouter.php(20): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#47 /dir/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(170): October\Rain\Router\CoreRouter->dispatch(Object(Illuminate\Http\Request))
#48 /dir/plugins/bedard/debugbar/vendor/illuminate/pipeline/Pipeline.php(130): Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}(Object(Illuminate\Http\Request))
#49 /dir/plugins/bedard/debugbar/vendor/barryvdh/laravel-debugbar/src/Middleware/InjectDebugbar.php(65): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#50 /dir/plugins/bedard/debugbar/vendor/illuminate/pipeline/Pipeline.php(171): Barryvdh\Debugbar\Middleware\InjectDebugbar->handle(Object(Illuminate\Http\Request), Object(Closure))
#51 /dir/plugins/offline/speedy/classes/middleware/CDNMiddleware.php(40): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#52 /dir/plugins/bedard/debugbar/vendor/illuminate/pipeline/Pipeline.php(171): OFFLINE\Speedy\Classes\Middleware\CDNMiddleware->handle(Object(Illuminate\Http\Request), Object(Closure))
#53 /dir/plugins/offline/speedy/classes/middleware/Http2Middleware.php(38): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#54 /dir/plugins/bedard/debugbar/vendor/illuminate/pipeline/Pipeline.php(171): OFFLINE\Speedy\Classes\Middleware\Http2Middleware->handle(Object(Illuminate\Http\Request), Object(Closure))
#55 /dir/plugins/offline/responsiveimages/classes/ResponsiveImagesMiddleware.php(30): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#56 /dir/plugins/bedard/debugbar/vendor/illuminate/pipeline/Pipeline.php(171): OFFLINE\ResponsiveImages\Classes\ResponsiveImagesMiddleware->handle(Object(Illuminate\Http\Request), Object(Closure))
#57 /dir/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(63): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#58 /dir/vendor/october/rain/src/Foundation/Http/Middleware/CheckForMaintenanceMode.php(24): Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle(Object(Illuminate\Http\Request), Object(Closure))
#59 /dir/plugins/bedard/debugbar/vendor/illuminate/pipeline/Pipeline.php(171): October\Rain\Foundation\Http\Middleware\CheckForMaintenanceMode->handle(Object(Illuminate\Http\Request), Object(Closure))
#60 /dir/plugins/vdlp/redirect/classes/RedirectMiddleware.php(64): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#61 /dir/plugins/bedard/debugbar/vendor/illuminate/pipeline/Pipeline.php(171): Vdlp\Redirect\Classes\RedirectMiddleware->handle(Object(Illuminate\Http\Request), Object(Closure))
#62 /dir/plugins/bedard/debugbar/vendor/illuminate/pipeline/Pipeline.php(105): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#63 /dir/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(145): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#64 /dir/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(110): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#65 /d/index.php(43): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#66 {main}  
```

**Comment by bennothommo** [comment]
Wow, that is a compound fracture of a method name :/

**Comment by bennothommo** [comment]
Fixed by https://github.com/octobercms/library/commit/13efd83fc9f10ff21d2b174ed6a5c033e9914699.
