### ISSUE TITLE
Twig macro import is broken

### ISSUE THREAD

**Issue by si-dge** [octobercms/october#5259]
- OctoberCMS Build: 468 `develop` branch
- PHP Version: 7.3.21
- Database Engine: mysql 5.7.25
- Plugins Installed: Rainlab.Pages, October.Demo, Lovata.Buddies, Lovata.Shopaholic, Lovata.Toolbox, Lovata.Goodnews (etc by Lovata) - last versions
- Cache driver: file

### Description:

Pages are not loading when develop theme with using twig macro (https://octobercms.com/docs/markup/tag-macro). No errors in the log. Just rendering a blank page. The list of twig cache includes: only the macro file and the page file:
- "/var/www/project/themes/demo/pages/home.htm";
- "/var/www/project/themes/demo/components/input/input.twig"; 

Yep, I use .twig extension, but I checked some alternatives: .htm, rename the folder as "macros" (like in doc) - it not solve problem. If I use macro path "/var/www/project/themes/demo/macros/form.htm", render throw Exception:
```
Next Twig\Error\RuntimeError: An exception has been thrown during the rendering of a template ("View [macros/form] not found.") in "/var/www/project/themes/demo/pages/home.htm" at line 4. in /var/www/project/vendor/twig/twig/src/Template.php:419
Stack trace:
#0 /var/www/project/vendor/twig/twig/src/Template.php(378): Twig\Template->displayWithErrorHandling(Array, Array)
#1 /var/www/project/vendor/twig/twig/src/Template.php(390): Twig\Template->display(Array)
#2 /var/www/project/modules/cms/classes/Controller.php(423): Twig\Template->render(Array)
#3 /var/www/project/modules/cms/classes/Controller.php(223): Cms\Classes\Controller->runPage(Object(Cms\Classes\Page))
#4 /var/www/project/modules/cms/classes/CmsController.php(50): Cms\Classes\Controller->run('/')
#5 [internal function]: Cms\Classes\CmsController->run('/')
#6 /var/www/project/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): call_user_func_array(Array, Array)
#7 /var/www/project/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(45): Illuminate\Routing\Controller->callAction('run', Array)
#8 /var/www/project/vendor/laravel/framework/src/Illuminate/Routing/Route.php(219): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(Cms\Classes\CmsController), 'run')
#9 /var/www/project/vendor/laravel/framework/src/Illuminate/Routing/Route.php(176): Illuminate\Routing\Route->runController()
#10 /var/www/project/vendor/laravel/framework/src/Illuminate/Routing/Router.php(681): Illuminate\Routing\Route->run()
#11 /var/www/project/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(130): Illuminate\Routing\Router->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#12 /var/www/project/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(41): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#13 /var/www/project/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\Routing\Middleware\SubstituteBindings->handle(Object(Illuminate\Http\Request), Object(Closure))
#14 /var/www/project/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#15 /var/www/project/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\View\Middleware\ShareErrorsFromSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#16 /var/www/project/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(56): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#17 /var/www/project/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\Session\Middleware\StartSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#18 /var/www/project/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#19 /var/www/project/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse->handle(Object(Illuminate\Http\Request), Object(Closure))
#20 /var/www/project/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(67): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#21 /var/www/project/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\Cookie\Middleware\EncryptCookies->handle(Object(Illuminate\Http\Request), Object(Closure))
#22 /var/www/project/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(105): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#23 /var/www/project/vendor/laravel/framework/src/Illuminate/Routing/Router.php(683): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#24 /var/www/project/vendor/laravel/framework/src/Illuminate/Routing/Router.php(658): Illuminate\Routing\Router->runRouteWithinStack(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request))
#25 /var/www/project/vendor/laravel/framework/src/Illuminate/Routing/Router.php(624): Illuminate\Routing\Router->runRoute(Object(Illuminate\Http\Request), Object(Illuminate\Routing\Route))
#26 /var/www/project/vendor/october/rain/src/Router/CoreRouter.php(20): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#27 /var/www/project/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(170): October\Rain\Router\CoreRouter->dispatch(Object(Illuminate\Http\Request))
#28 /var/www/project/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(130): Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}(Object(Illuminate\Http\Request))
#29 /var/www/project/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(63): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#30 /var/www/project/vendor/october/rain/src/Foundation/Http/Middleware/CheckForMaintenanceMode.php(25): Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle(Object(Illuminate\Http\Request), Object(Closure))
#31 /var/www/project/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): October\Rain\Foundation\Http\Middleware\CheckForMaintenanceMode->handle(Object(Illuminate\Http\Request), Object(Closure))
#32 /var/www/project/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(105): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#33 /var/www/project/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(145): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#34 /var/www/project/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(110): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#35 /var/www/project/index.php(43): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#36 {main}
```

I use the macro from doc example (input).

I tested this on build 459 and the macro worked there.

### Steps To Reproduce:

0. Use demo theme.

1. Create file `./themes/demo/components/input/input.twig` or `./themes/demo/macros/form.htm`:
```
{% macro input(name, value, type = "text", size = 20) %}
    <input type="{{ type }}" name="{{ name }}" value="{{ value|e }}" size="{{ size }}">
{% endmacro %}
```

2. Add import in file `./themes/demo/pages/home.htm`:
```
{% from '../components/input/input.twig' import input %}
```
or
```
{% import 'macros/form' as form %}
```

3. Call macro in file `./themes/mytheme/pages/home.htm`
```
<p>{{ input('username') }}</p>
```
or
```
<p>{{ form.input('username') }}</p>
```

### Flow To Solve:

It work, if set full path to the macro file like
```{% from '/var/www/project/themes/demo/components/input/input.twig' import input %}```

**Comment by LukeTowers** [comment]
Firstly, .twig is not a supported extension in the themes, .htm is the only valid extension. Secondly, the docs state

> Macros can be defined in a **theme partial** and imported by name. To import the macros from a partial called macros/form.htm, simply pass the name after the import tag quoted as a string.

Try defining your macro in `theme/partials/macros/form.htm` and `import 'macros/form'`.

**Comment by si-dge** [comment]
Yes, it work.

Interesting why on version 459 it works when importing from another folder. And with twig extesion

**Comment by LukeTowers** [comment]
It never should have. There have been various security enhancements to lock down how partials and other templates are loaded, so that would be my guess as to why it changed.

**Comment by si-dge** [comment]
I use twig because the theme develop separately with webpack. In this case october layout not useable. Maybe, you can give advice how is better

**Comment by LukeTowers** [comment]
I'm not sure what you mean.
