### ISSUE TITLE
Check if template $code is string because use laravel notification $code is HtmlString.

### ISSUE THREAD

**Issue by bossleem** [octobercms/october#5482]
- OctoberCMS Build: v1.1.1 
- PHP Version: 7.4
- Database Engine: MySql 
- Plugins Installed: https://github.com/panakour/oc-backup-plugin 

### Description:

```php
public function addContentToMailer($message, $code, $data, $plainOnly = false)
    {
        if (!is_string($code)) return false;
        if (isset($this->templateCache[$code])) {
            $template = $this->templateCache[$code];
        } else {
            $this->templateCache[$code] = $template = MailTemplate::findOrMakeTemplate($code);
        }

        if (!$template) {
            return false;
        }

        $this->addContentToMailerInternal($message, $template, $data, $plainOnly);

        return true;
    }
```

**Comment by kunvn** [comment]
public function addContentToMailer($message, $code, $data, $plainOnly = false)
    {
        if (!is_string($code)) return false;
        if (isset($this->templateCache[$code])) {
            $template = $this->templateCache[$code];
        } else {
            $this->templateCache[$code] = $template = MailTemplate::findOrMakeTemplate($code);
        }

        if (!$template) {
            return false;
        }

        $this->addContentToMailerInternal($message, $template, $data, $plainOnly);

        return true;
    }

**Comment by kunvn** [comment]
##

public function addContentToMailer($message, $code, $data, $plainOnly = false)
    {
        if (!is_string($code)) return false;
        if (isset($this->templateCache[$code])) {
            $template = $this->templateCache[$code];
        } else {
            $this->templateCache[$code] = $template = MailTemplate::findOrMakeTemplate($code);
        }

        if (!$template) {
            return false;
        }

        $this->addContentToMailerInternal($message, $template, $data, $plainOnly);

        return true;
    } # #

**Comment by LukeTowers** [comment]
What?

**Comment by bossleem** [comment]
i'm sorry i'm vietnamese, my english is bad so it is difficult to express what i am saying.

**Comment by LukeTowers** [comment]
You haven't said anything yet, you've only posted code. No idea what the problem is that you're trying to report.

**Comment by bossleem** [comment]
I use the package https://github.com/spatie/laravel-backup



when I use the command line "php artisan backup: run" to backup the data.
In the package I use, after successfully saving it will send email notification about the backup.
The problem is sending mail at "System \ Classes \ MailManager" with method "addContentToMailer". The code variable is not a string, so checking the code variable is in the template array will fail.




```
[2021-01-30 16:39:54] club168.ERROR: ErrorException: Illegal offset type in isset or empty in D:\PHP\kun\modules\system\classes\MailManager.php:85
Stack trace:
#0 D:\PHP\kun\modules\system\classes\MailManager.php(85): Illuminate\Foundation\Bootstrap\HandleExceptions->handleError()
#1 D:\PHP\kun\modules\system\ServiceProvider.php(365): System\Classes\MailManager->addContentToMailer()
#2 D:\PHP\kun\vendor\october\rain\src\Events\Dispatcher.php(417): System\ServiceProvider->System\{closure}()
#3 D:\PHP\kun\vendor\october\rain\src\Events\Dispatcher.php(260): October\Rain\Events\Dispatcher->October\Rain\Events\{closure}()
#4 D:\PHP\kun\vendor\october\rain\src\Events\Dispatcher.php(226): October\Rain\Events\Dispatcher->dispatch()
#5 D:\PHP\kun\vendor\laravel\framework\src\Illuminate\Support\Facades\Facade.php(261): October\Rain\Events\Dispatcher->fire()
#6 D:\PHP\kun\vendor\october\rain\src\Mail\Mailer.php(403): Illuminate\Support\Facades\Facade::__callStatic()
#7 D:\PHP\kun\vendor\october\rain\src\Mail\Mailer.php(77): October\Rain\Mail\Mailer->addContent()
#8 D:\PHP\kun\vendor\laravel\framework\src\Illuminate\Notifications\Channels\MailChannel.php(65): October\Rain\Mail\Mailer->send()
#9 D:\PHP\kun\vendor\laravel\framework\src\Illuminate\Notifications\NotificationSender.php(148): Illuminate\Notifications\Channels\MailChannel->send()
#10 D:\PHP\kun\vendor\laravel\framework\src\Illuminate\Notifications\NotificationSender.php(106): Illuminate\Notifications\NotificationSender->sendToNotifiable()
#11 D:\PHP\kun\vendor\laravel\framework\src\Illuminate\Support\Traits\Localizable.php(19): Illuminate\Notifications\NotificationSender->Illuminate\Notifications\{closure}()
#12 D:\PHP\kun\vendor\laravel\framework\src\Illuminate\Notifications\NotificationSender.php(109): Illuminate\Notifications\NotificationSender->withLocale()
#13 D:\PHP\kun\vendor\laravel\framework\src\Illuminate\Notifications\NotificationSender.php(79): Illuminate\Notifications\NotificationSender->sendNow()
#14 D:\PHP\kun\vendor\laravel\framework\src\Illuminate\Notifications\ChannelManager.php(39): Illuminate\Notifications\NotificationSender->send()
#15 D:\PHP\kun\vendor\laravel\framework\src\Illuminate\Notifications\RoutesNotifications.php(18): Illuminate\Notifications\ChannelManager->send()
#16 D:\PHP\kun\plugins\panakour\backup\vendor\spatie\laravel-backup\src\Notifications\EventHandler.php(33): Spatie\Backup\Notifications\Notifiable->notify()
#17 D:\PHP\kun\vendor\october\rain\src\Events\Dispatcher.php(417): Spatie\Backup\Notifications\EventHandler->Spatie\Backup\Notifications\{closure}()
#18 D:\PHP\kun\vendor\october\rain\src\Events\Dispatcher.php(260): October\Rain\Events\Dispatcher->October\Rain\Events\{closure}()
#19 D:\PHP\kun\vendor\laravel\framework\src\Illuminate\Foundation\helpers.php(477): October\Rain\Events\Dispatcher->dispatch()
#20 D:\PHP\kun\plugins\october\demo\console\Test.php(35): event()
#21 [internal function]: October\Demo\Console\Test->handle()
#22 D:\PHP\kun\vendor\laravel\framework\src\Illuminate\Container\BoundMethod.php(32): call_user_func_array()
#23 D:\PHP\kun\vendor\laravel\framework\src\Illuminate\Container\Util.php(37): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#24 D:\PHP\kun\vendor\laravel\framework\src\Illuminate\Container\BoundMethod.php(90): Illuminate\Container\Util::unwrapIfClosure()
#25 D:\PHP\kun\vendor\laravel\framework\src\Illuminate\Container\BoundMethod.php(34): Illuminate\Container\BoundMethod::callBoundMethod()
#26 D:\PHP\kun\vendor\laravel\framework\src\Illuminate\Container\Container.php(590): Illuminate\Container\BoundMethod::call()
#27 D:\PHP\kun\vendor\laravel\framework\src\Illuminate\Console\Command.php(134): Illuminate\Container\Container->call()
#28 D:\PHP\kun\vendor\symfony\console\Command\Command.php(255): Illuminate\Console\Command->execute()
#29 D:\PHP\kun\vendor\laravel\framework\src\Illuminate\Console\Command.php(121): Symfony\Component\Console\Command\Command->run()
#30 D:\PHP\kun\vendor\symfony\console\Application.php(1009): Illuminate\Console\Command->run()
#31 D:\PHP\kun\vendor\symfony\console\Application.php(273): Symfony\Component\Console\Application->doRunCommand()
#32 D:\PHP\kun\vendor\symfony\console\Application.php(149): Symfony\Component\Console\Application->doRun()
#33 D:\PHP\kun\vendor\laravel\framework\src\Illuminate\Console\Application.php(93): Symfony\Component\Console\Application->run()
#34 D:\PHP\kun\vendor\laravel\framework\src\Illuminate\Foundation\Console\Kernel.php(131): Illuminate\Console\Application->run()
#35 D:\PHP\kun\artisan(35): Illuminate\Foundation\Console\Kernel->handle()
#36 {main}  
[2021-01-30 17:07:22] club168.ERROR: Symfony\Component\Debug\Exception\FatalThrowableError: Class 'KSystem\Event' not found in D:\PHP\kun\modules\ksystem\ServiceProvider.php:37
Stack trace:
#0 D:\PHP\kun\modules\system\ServiceProvider.php(57): KSystem\ServiceProvider->registerMailer()
#1 D:\PHP\kun\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(616): System\ServiceProvider->register()
#2 D:\PHP\kun\vendor\laravel\framework\src\Illuminate\Foundation\ProviderRepository.php(75): Illuminate\Foundation\Application->register()
#3 D:\PHP\kun\vendor\october\rain\src\Foundation\Application.php(401): Illuminate\Foundation\ProviderRepository->load()
#4 D:\PHP\kun\vendor\october\rain\src\Foundation\Application.php(409): October\Rain\Foundation\Application->registerConfiguredProviders()
#5 D:\PHP\kun\vendor\laravel\framework\src\Illuminate\Foundation\Bootstrap\RegisterProviders.php(17): October\Rain\Foundation\Application->registerConfiguredProviders()
#6 D:\PHP\kun\vendor\october\rain\src\Foundation\Application.php(127): Illuminate\Foundation\Bootstrap\RegisterProviders->bootstrap()
#7 D:\PHP\kun\vendor\laravel\framework\src\Illuminate\Foundation\Console\Kernel.php(320): October\Rain\Foundation\Application->bootstrapWith()
#8 D:\PHP\kun\vendor\laravel\framework\src\Illuminate\Foundation\Console\Kernel.php(129): Illuminate\Foundation\Console\Kernel->bootstrap()
#9 D:\PHP\kun\artisan(35): Illuminate\Foundation\Console\Kernel->handle()
#10 {main}  
[2021-01-30 17:07:47] club168.ERROR: Swift_TransportException: Expected response code 250 but got code "550", with message "550 5.7.1 Relaying denied
" in D:\PHP\kun\vendor\swiftmailer\swiftmailer\lib\classes\Swift\Transport\AbstractSmtpTransport.php:460
Stack trace:
#0 D:\PHP\kun\vendor\swiftmailer\swiftmailer\lib\classes\Swift\Transport\AbstractSmtpTransport.php(345): Swift_Transport_AbstractSmtpTransport->assertResponseCode()
#1 D:\PHP\kun\vendor\swiftmailer\swiftmailer\lib\classes\Swift\Transport\EsmtpTransport.php(305): Swift_Transport_AbstractSmtpTransport->executeCommand()
#2 D:\PHP\kun\vendor\swiftmailer\swiftmailer\lib\classes\Swift\Transport\AbstractSmtpTransport.php(393): Swift_Transport_EsmtpTransport->executeCommand()
#3 D:\PHP\kun\vendor\swiftmailer\swiftmailer\lib\classes\Swift\Transport\AbstractSmtpTransport.php(500): Swift_Transport_AbstractSmtpTransport->doDataCommand()
#4 D:\PHP\kun\vendor\swiftmailer\swiftmailer\lib\classes\Swift\Transport\AbstractSmtpTransport.php(519): Swift_Transport_AbstractSmtpTransport->doMailTransaction()
#5 D:\PHP\kun\vendor\swiftmailer\swiftmailer\lib\classes\Swift\Transport\AbstractSmtpTransport.php(206): Swift_Transport_AbstractSmtpTransport->sendTo()
#6 D:\PHP\kun\vendor\swiftmailer\swiftmailer\lib\classes\Swift\Mailer.php(71): Swift_Transport_AbstractSmtpTransport->send()
#7 D:\PHP\kun\vendor\laravel\framework\src\Illuminate\Mail\Mailer.php(488): Swift_Mailer->send()
#8 D:\PHP\kun\vendor\october\rain\src\Mail\Mailer.php(115): Illuminate\Mail\Mailer->sendSwiftMessage()
#9 D:\PHP\kun\vendor\laravel\framework\src\Illuminate\Notifications\Channels\MailChannel.php(65): October\Rain\Mail\Mailer->send()
#10 D:\PHP\kun\vendor\laravel\framework\src\Illuminate\Notifications\NotificationSender.php(148): Illuminate\Notifications\Channels\MailChannel->send()
#11 D:\PHP\kun\vendor\laravel\framework\src\Illuminate\Notifications\NotificationSender.php(106): Illuminate\Notifications\NotificationSender->sendToNotifiable()
#12 D:\PHP\kun\vendor\laravel\framework\src\Illuminate\Support\Traits\Localizable.php(19): Illuminate\Notifications\NotificationSender->Illuminate\Notifications\{closure}()
#13 D:\PHP\kun\vendor\laravel\framework\src\Illuminate\Notifications\NotificationSender.php(109): Illuminate\Notifications\NotificationSender->withLocale()
#14 D:\PHP\kun\vendor\laravel\framework\src\Illuminate\Notifications\NotificationSender.php(79): Illuminate\Notifications\NotificationSender->sendNow()
#15 D:\PHP\kun\vendor\laravel\framework\src\Illuminate\Notifications\ChannelManager.php(39): Illuminate\Notifications\NotificationSender->send()
#16 D:\PHP\kun\vendor\laravel\framework\src\Illuminate\Notifications\RoutesNotifications.php(18): Illuminate\Notifications\ChannelManager->send()
#17 D:\PHP\kun\plugins\panakour\backup\vendor\spatie\laravel-backup\src\Notifications\EventHandler.php(33): Spatie\Backup\Notifications\Notifiable->notify()
#18 D:\PHP\kun\vendor\october\rain\src\Events\Dispatcher.php(417): Spatie\Backup\Notifications\EventHandler->Spatie\Backup\Notifications\{closure}()
#19 D:\PHP\kun\vendor\october\rain\src\Events\Dispatcher.php(260): October\Rain\Events\Dispatcher->October\Rain\Events\{closure}()
#20 D:\PHP\kun\vendor\laravel\framework\src\Illuminate\Foundation\helpers.php(477): October\Rain\Events\Dispatcher->dispatch()
#21 D:\PHP\kun\plugins\october\demo\console\Test.php(35): event()
#22 [internal function]: October\Demo\Console\Test->handle()
#23 D:\PHP\kun\vendor\laravel\framework\src\Illuminate\Container\BoundMethod.php(32): call_user_func_array()
#24 D:\PHP\kun\vendor\laravel\framework\src\Illuminate\Container\Util.php(37): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#25 D:\PHP\kun\vendor\laravel\framework\src\Illuminate\Container\BoundMethod.php(90): Illuminate\Container\Util::unwrapIfClosure()
#26 D:\PHP\kun\vendor\laravel\framework\src\Illuminate\Container\BoundMethod.php(34): Illuminate\Container\BoundMethod::callBoundMethod()
#27 D:\PHP\kun\vendor\laravel\framework\src\Illuminate\Container\Container.php(590): Illuminate\Container\BoundMethod::call()
#28 D:\PHP\kun\vendor\laravel\framework\src\Illuminate\Console\Command.php(134): Illuminate\Container\Container->call()
#29 D:\PHP\kun\vendor\symfony\console\Command\Command.php(255): Illuminate\Console\Command->execute()
#30 D:\PHP\kun\vendor\laravel\framework\src\Illuminate\Console\Command.php(121): Symfony\Component\Console\Command\Command->run()
#31 D:\PHP\kun\vendor\symfony\console\Application.php(1009): Illuminate\Console\Command->run()
#32 D:\PHP\kun\vendor\symfony\console\Application.php(273): Symfony\Component\Console\Application->doRunCommand()
#33 D:\PHP\kun\vendor\symfony\console\Application.php(149): Symfony\Component\Console\Application->doRun()
#34 D:\PHP\kun\vendor\laravel\framework\src\Illuminate\Console\Application.php(93): Symfony\Component\Console\Application->run()
#35 D:\PHP\kun\vendor\laravel\framework\src\Illuminate\Foundation\Console\Kernel.php(131): Illuminate\Console\Application->run()
#36 D:\PHP\kun\artisan(35): Illuminate\Foundation\Console\Kernel->handle()
#37 {main}  
[2021-01-31 08:43:35] club168.ERROR: ErrorException: Illegal offset type in isset or empty in D:\PHP\kun\modules\system\classes\MailManager.php:85
Stack trace:
#0 D:\PHP\kun\modules\system\classes\MailManager.php(85): Illuminate\Foundation\Bootstrap\HandleExceptions->handleError()
#1 D:\PHP\kun\modules\system\ServiceProvider.php(365): System\Classes\MailManager->addContentToMailer()
#2 D:\PHP\kun\vendor\october\rain\src\Events\Dispatcher.php(417): System\ServiceProvider->System\{closure}()
#3 D:\PHP\kun\vendor\october\rain\src\Events\Dispatcher.php(260): October\Rain\Events\Dispatcher->October\Rain\Events\{closure}()
#4 D:\PHP\kun\vendor\october\rain\src\Events\Dispatcher.php(226): October\Rain\Events\Dispatcher->dispatch()
#5 D:\PHP\kun\vendor\laravel\framework\src\Illuminate\Support\Facades\Facade.php(261): October\Rain\Events\Dispatcher->fire()
#6 D:\PHP\kun\vendor\october\rain\src\Mail\Mailer.php(403): Illuminate\Support\Facades\Facade::__callStatic()
#7 D:\PHP\kun\vendor\october\rain\src\Mail\Mailer.php(77): October\Rain\Mail\Mailer->addContent()
#8 D:\PHP\kun\vendor\laravel\framework\src\Illuminate\Notifications\Channels\MailChannel.php(65): October\Rain\Mail\Mailer->send()
#9 D:\PHP\kun\vendor\laravel\framework\src\Illuminate\Notifications\NotificationSender.php(148): Illuminate\Notifications\Channels\MailChannel->send()
#10 D:\PHP\kun\vendor\laravel\framework\src\Illuminate\Notifications\NotificationSender.php(106): Illuminate\Notifications\NotificationSender->sendToNotifiable()
#11 D:\PHP\kun\vendor\laravel\framework\src\Illuminate\Support\Traits\Localizable.php(19): Illuminate\Notifications\NotificationSender->Illuminate\Notifications\{closure}()
#12 D:\PHP\kun\vendor\laravel\framework\src\Illuminate\Notifications\NotificationSender.php(109): Illuminate\Notifications\NotificationSender->withLocale()
#13 D:\PHP\kun\vendor\laravel\framework\src\Illuminate\Notifications\NotificationSender.php(79): Illuminate\Notifications\NotificationSender->sendNow()
#14 D:\PHP\kun\vendor\laravel\framework\src\Illuminate\Notifications\ChannelManager.php(39): Illuminate\Notifications\NotificationSender->send()
#15 D:\PHP\kun\vendor\laravel\framework\src\Illuminate\Notifications\RoutesNotifications.php(18): Illuminate\Notifications\ChannelManager->send()
#16 D:\PHP\kun\plugins\panakour\backup\vendor\spatie\laravel-backup\src\Notifications\EventHandler.php(33): Spatie\Backup\Notifications\Notifiable->notify()
#17 D:\PHP\kun\vendor\october\rain\src\Events\Dispatcher.php(417): Spatie\Backup\Notifications\EventHandler->Spatie\Backup\Notifications\{closure}()
#18 D:\PHP\kun\vendor\october\rain\src\Events\Dispatcher.php(260): October\Rain\Events\Dispatcher->October\Rain\Events\{closure}()
#19 D:\PHP\kun\vendor\laravel\framework\src\Illuminate\Foundation\helpers.php(477): October\Rain\Events\Dispatcher->dispatch()
#20 D:\PHP\kun\plugins\october\demo\console\Test.php(35): event()
#21 [internal function]: October\Demo\Console\Test->handle()
#22 D:\PHP\kun\vendor\laravel\framework\src\Illuminate\Container\BoundMethod.php(32): call_user_func_array()
#23 D:\PHP\kun\vendor\laravel\framework\src\Illuminate\Container\Util.php(37): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#24 D:\PHP\kun\vendor\laravel\framework\src\Illuminate\Container\BoundMethod.php(90): Illuminate\Container\Util::unwrapIfClosure()
#25 D:\PHP\kun\vendor\laravel\framework\src\Illuminate\Container\BoundMethod.php(34): Illuminate\Container\BoundMethod::callBoundMethod()
#26 D:\PHP\kun\vendor\laravel\framework\src\Illuminate\Container\Container.php(590): Illuminate\Container\BoundMethod::call()
#27 D:\PHP\kun\vendor\laravel\framework\src\Illuminate\Console\Command.php(134): Illuminate\Container\Container->call()
#28 D:\PHP\kun\vendor\symfony\console\Command\Command.php(255): Illuminate\Console\Command->execute()
#29 D:\PHP\kun\vendor\laravel\framework\src\Illuminate\Console\Command.php(121): Symfony\Component\Console\Command\Command->run()
#30 D:\PHP\kun\vendor\symfony\console\Application.php(1009): Illuminate\Console\Command->run()
#31 D:\PHP\kun\vendor\symfony\console\Application.php(273): Symfony\Component\Console\Application->doRunCommand()
#32 D:\PHP\kun\vendor\symfony\console\Application.php(149): Symfony\Component\Console\Application->doRun()
#33 D:\PHP\kun\vendor\laravel\framework\src\Illuminate\Console\Application.php(93): Symfony\Component\Console\Application->run()
#34 D:\PHP\kun\vendor\laravel\framework\src\Illuminate\Foundation\Console\Kernel.php(131): Illuminate\Console\Application->run()
#35 D:\PHP\kun\artisan(35): Illuminate\Foundation\Console\Kernel->handle()
#36 {main}  
```

**Comment by adrenth** [comment]
The method `public function addContentToMailer($message, $code, $data, $plainOnly = false)` has no typed parameters, so `$code` could contain any value provided.

@kunvn suggests adding this code to prevent an error will be thrown if `$code` is anything but a string.

```php
if (!is_string($code)) { 
  return false;
}
```

**Comment by daftspunk** [comment]
Got it. Thanks @adrenth
