### ISSUE TITLE
Installing october cms on PHP 8 fails

### ISSUE THREAD

**Issue by ghost** [octobercms/october#5550]
- OctoberCMS Build: 471 (download from http://octobercms.com/download)
- PHP Version: PHP 8.0.3
- Database Engine: MySQL (Ver 8.0.23 for Linux on x86_64 (MySQL Community Server - GPL))
- Plugins Installed: None yet just initial installation

### Description:

![Screenshot_2021-04-03 October Installation](https://user-images.githubusercontent.com/56940608/113488614-7c4cbb80-94bf-11eb-9bcd-b27c889f8da2.png)

![Screenshot_2021-04-03 October Installation](https://user-images.githubusercontent.com/56940608/113488540-1bbd7e80-94bf-11eb-9ab9-128ac05146b8.png)

### Steps To Reproduce:

Install:
* Debian GNU/Linux 10 (buster)
* nginx version: nginx/1.19.9
* PHP 8.0.3
* apt install php8.0-fpm php8.0-curl php8.0-mbstring php8.0-zip php8.0-gd php8.0-xml php8.0-mysql
* MySQL Community Server - GPL Ver 8.0.23 for Linux on x86_64 (from https://dev.mysql.com/downloads/repo/apt/)

Configure everything and try to install october cms (How do you want to set up your site?->Start from scratch)
Logs from nginx:
```
2021/04/03 21:32:47 [error] 1043#1043: *1 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Declaration of Doctrine\DBAL\Driver\PDOConnection::query() must be compatible with PDO::query(string $query, ?int $fetchMode = null, mixed ...$fetchModeArgs) in /usr/share/nginx/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php on line 86PHP message: PHP Fatal error:  Uncaught ErrorException: Method ReflectionParameter::getClass() is deprecated in /usr/share/nginx/html/vendor/laravel/framework/src/Illuminate/Container/Container.php:811
Stack trace:
#0 /usr/share/nginx/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(811): Illuminate\Foundation\Bootstrap\HandleExceptions->handleError()
#1 /usr/share/nginx/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(780): Illuminate\Container\Container->resolveDependencies()
#2 /usr/share/nginx/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(631): Illuminate\Container\Container->build()
#3 /usr/share/nginx/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(586): Illuminate\Container\Container->resolve()
#4 /usr/share/nginx/html/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(732): Illuminate\Container\Container->make()
#5 /usr/share/nginx/html/vendor/october/rain/src/Foundation/Application.php(188)" while reading response header from upstream, client: x.x.x.x, server: x.x.x.x, request: "POST /install.php HTTP/2.0", upstream: "fastcgi://unix:/var/run/php/php8.0-fpm.sock:", host: "x.x.x.x", referrer: "https://x.x.x.x/install.php"
```

Logs from install_files/install.log:
```
.=====================================================================.
                                                                       
  .d8888b.   .o8888b.  db  .d8888b.  d8888b. d88888b d8888b.  .d888b.  
 .8P    Y8. d8P    Y8  88 .8P    Y8. 88  `8D 88'     88  `8D .8P , Y8. 
 88      88 8P     .ooo88 88      88 88oooY' 88oooo  88oobY' 88  |  88 
 88      88 8b     `~~~88 88      88 88~~~b. 88~~~~  88`8b   88  |/ 88 
 `8b    d8' Y8b    d8  88 `8b    d8' 88   8D 88.     88 `88. `8b | d8' 
  `Y8888P'   `Y8888P'  YP  `Y8888P'  Y8888P' Y88888P 88   YD  `Y888P'  
                                                                       
`========================== INSTALLATION LOG ========================='

[2021/04/03 09:28:41] Host: Linux x.x.x.x 4.19.0-16-amd64 #1 SMP Debian 4.19.181-1 (2021-03-19) x86_64
[2021/04/03 09:28:41] PHP version: 8.0.3
[2021/04/03 09:28:41] Server software: nginx/1.19.9
[2021/04/03 09:28:41] Operating system: Linux
[2021/04/03 09:28:41] Memory limit: 128M
[2021/04/03 09:28:41] Max execution time: 3600
.============================ POST REQUEST ==========================.
[2021/04/03 09:28:41] Postback payload: Array
(
    [code] => phpVersion
    [handler] => onCheckRequirement
)

[2021/04/03 09:28:41] System check: phpVersion
[2021/04/03 09:28:41] Requirement phpVersion +OK
[2021/04/03 09:28:41] Execute handler (onCheckRequirement): Array
(
    [result] => 1
)

.============================ POST REQUEST ==========================.
[2021/04/03 09:28:41] Postback payload: Array
(
    [code] => curlLibrary
    [handler] => onCheckRequirement
)

[2021/04/03 09:28:41] System check: curlLibrary
[2021/04/03 09:28:41] Requirement curlLibrary +OK
[2021/04/03 09:28:41] Execute handler (onCheckRequirement): Array
(
    [result] => 1
)

.============================ POST REQUEST ==========================.
[2021/04/03 09:28:42] Postback payload: Array
(
    [code] => jsonLibrary
    [handler] => onCheckRequirement
)

[2021/04/03 09:28:42] System check: jsonLibrary
[2021/04/03 09:28:42] Requirement jsonLibrary +OK
[2021/04/03 09:28:42] Execute handler (onCheckRequirement): Array
(
    [result] => 1
)

.============================ POST REQUEST ==========================.
[2021/04/03 09:28:42] Postback payload: Array
(
    [code] => liveConnection
    [handler] => onCheckRequirement
)

[2021/04/03 09:28:42] System check: liveConnection
[2021/04/03 09:28:43] Server request: ping
[2021/04/03 09:28:43] Request information: Array
(
    [url] => http://gateway.octobercms.com/api/ping
    [content_type] => application/json
    [http_code] => 200
    [header_size] => 652
    [request_size] => 183
    [filetime] => -1
    [ssl_verify_result] => 0
    [redirect_count] => 0
    [total_time] => 0.549425
    [namelookup_time] => 0.00642
    [connect_time] => 0.192649
    [pretransfer_time] => 0.192749
    [size_upload] => 44
    [size_download] => 12
    [speed_download] => 21
    [speed_upload] => 80
    [download_content_length] => -1
    [upload_content_length] => 44
    [starttransfer_time] => 0.549373
    [redirect_time] => 0
    [redirect_url] => 
    [primary_ip] => 52.24.36.22
    [certinfo] => Array
        (
        )

    [primary_port] => 80
    [local_ip] => x.x.x.x
    [local_port] => 42256
    [http_version] => 2
    [protocol] => 1
    [ssl_verifyresult] => 0
    [scheme] => HTTP
    [appconnect_time_us] => 0
    [connect_time_us] => 192649
    [namelookup_time_us] => 6420
    [pretransfer_time_us] => 192749
    [redirect_time_us] => 0
    [starttransfer_time_us] => 549373
    [total_time_us] => 549425
)

[2021/04/03 09:28:43] Requirement liveConnection +OK
[2021/04/03 09:28:43] Execute handler (onCheckRequirement): Array
(
    [result] => 1
)

.============================ POST REQUEST ==========================.
[2021/04/03 09:28:43] Postback payload: Array
(
    [code] => writePermission
    [handler] => onCheckRequirement
)

[2021/04/03 09:28:43] System check: writePermission
[2021/04/03 09:28:43] Requirement writePermission +OK
[2021/04/03 09:28:43] Execute handler (onCheckRequirement): Array
(
    [result] => 1
)

.============================ POST REQUEST ==========================.
[2021/04/03 09:28:44] Postback payload: Array
(
    [code] => pdoLibrary
    [handler] => onCheckRequirement
)

[2021/04/03 09:28:44] System check: pdoLibrary
[2021/04/03 09:28:44] Requirement pdoLibrary +OK
[2021/04/03 09:28:44] Execute handler (onCheckRequirement): Array
(
    [result] => 1
)

.============================ POST REQUEST ==========================.
[2021/04/03 09:28:44] Postback payload: Array
(
    [code] => mbstringLibrary
    [handler] => onCheckRequirement
)

[2021/04/03 09:28:44] System check: mbstringLibrary
[2021/04/03 09:28:44] Requirement mbstringLibrary +OK
[2021/04/03 09:28:44] Execute handler (onCheckRequirement): Array
(
    [result] => 1
)

.============================ POST REQUEST ==========================.
[2021/04/03 09:28:45] Postback payload: Array
(
    [code] => fileinfoLibrary
    [handler] => onCheckRequirement
)

[2021/04/03 09:28:45] System check: fileinfoLibrary
[2021/04/03 09:28:45] Requirement fileinfoLibrary +OK
[2021/04/03 09:28:45] Execute handler (onCheckRequirement): Array
(
    [result] => 1
)

.============================ POST REQUEST ==========================.
[2021/04/03 09:28:45] Postback payload: Array
(
    [code] => sslLibrary
    [handler] => onCheckRequirement
)

[2021/04/03 09:28:45] System check: sslLibrary
[2021/04/03 09:28:45] Requirement sslLibrary +OK
[2021/04/03 09:28:45] Execute handler (onCheckRequirement): Array
(
    [result] => 1
)

.============================ POST REQUEST ==========================.
[2021/04/03 09:28:46] Postback payload: Array
(
    [code] => gdLibrary
    [handler] => onCheckRequirement
)

[2021/04/03 09:28:46] System check: gdLibrary
[2021/04/03 09:28:46] Requirement gdLibrary +OK
[2021/04/03 09:28:46] Execute handler (onCheckRequirement): Array
(
    [result] => 1
)

.============================ POST REQUEST ==========================.
[2021/04/03 09:28:46] Postback payload: Array
(
    [code] => zipLibrary
    [handler] => onCheckRequirement
)

[2021/04/03 09:28:46] System check: zipLibrary
[2021/04/03 09:28:46] Requirement zipLibrary +OK
[2021/04/03 09:28:46] Execute handler (onCheckRequirement): Array
(
    [result] => 1
)

.============================ POST REQUEST ==========================.
[2021/04/03 09:28:47] Postback payload: Array
(
    [code] => filterLibrary
    [handler] => onCheckRequirement
)

[2021/04/03 09:28:47] System check: filterLibrary
[2021/04/03 09:28:47] Requirement filterLibrary +OK
[2021/04/03 09:28:47] Execute handler (onCheckRequirement): Array
(
    [result] => 1
)

.============================ POST REQUEST ==========================.
[2021/04/03 09:28:47] Postback payload: Array
(
    [code] => hashLibrary
    [handler] => onCheckRequirement
)

[2021/04/03 09:28:47] System check: hashLibrary
[2021/04/03 09:28:47] Requirement hashLibrary +OK
[2021/04/03 09:28:47] Execute handler (onCheckRequirement): Array
(
    [result] => 1
)

.============================ POST REQUEST ==========================.
[2021/04/03 09:28:48] Postback payload: Array
(
    [code] => allowUrlFopenConfig
    [handler] => onCheckRequirement
)

[2021/04/03 09:28:48] System check: allowUrlFopenConfig
[2021/04/03 09:28:48] Requirement allowUrlFopenConfig +OK
[2021/04/03 09:28:48] Execute handler (onCheckRequirement): Array
(
    [result] => 1
)

.============================ POST REQUEST ==========================.
[2021/04/03 09:29:38] Postback payload: Array
(
    [db_type] => mysql
    [db_host] => localhost
    [db_port] => 3306
    [db_name] => octoberdb
    [db_user] => octoberdb
    [db_pass] => *******
    [admin_first_name] => Admin
    [admin_last_name] => Person
    [admin_email] => *******@*****.com
    [admin_login] => admin
    [admin_password] => *******
    [admin_confirm_password] => *******
    [backend_uri] => /backend
    [encryption_code] => *******
    [file_mask] => 644
    [folder_mask] => 755
    [handler] => onValidateDatabase
)

.============================ POST REQUEST ==========================.
[2021/04/03 09:29:38] Postback payload: Array
(
    [db_type] => mysql
    [db_host] => localhost
    [db_port] => 3306
    [db_name] => octoberdb
    [db_user] => octoberdb
    [db_pass] => *******
    [admin_first_name] => Admin
    [admin_last_name] => Person
    [admin_email] => *******@*****.com
    [admin_login] => admin
    [admin_password] => *******
    [admin_confirm_password] => *******
    [backend_uri] => /backend
    [encryption_code] => *******
    [file_mask] => 644
    [folder_mask] => 755
    [handler] => onValidateAdminAccount
)

.============================ POST REQUEST ==========================.
[2021/04/03 09:29:38] Postback payload: Array
(
    [db_type] => mysql
    [db_host] => localhost
    [db_port] => 3306
    [db_name] => octoberdb
    [db_user] => octoberdb
    [db_pass] => *******
    [admin_first_name] => Admin
    [admin_last_name] => Person
    [admin_email] => *******@*****.com
    [admin_login] => admin
    [admin_password] => *******
    [admin_confirm_password] => *******
    [backend_uri] => /backend
    [encryption_code] => *******
    [file_mask] => 644
    [folder_mask] => 755
    [handler] => onValidateAdvancedConfig
)

.============================ POST REQUEST ==========================.
[2021/04/03 09:29:39] Postback payload: Array
(
    [step] => getMetaData
    [meta] => 
    [handler] => onInstallStep
)

[2021/04/03 09:29:39] Install step: getMetaData
[2021/04/03 09:29:40] Server request: core/install
[2021/04/03 09:29:40] Request information: Array
(
    [url] => http://gateway.octobercms.com/api/core/install
    [content_type] => application/json
    [http_code] => 200
    [header_size] => 652
    [request_size] => 191
    [filetime] => -1
    [ssl_verify_result] => 0
    [redirect_count] => 0
    [total_time] => 0.708746
    [namelookup_time] => 0.029364
    [connect_time] => 0.214726
    [pretransfer_time] => 0.214822
    [size_upload] => 44
    [size_download] => 132
    [speed_download] => 186
    [speed_upload] => 62
    [download_content_length] => -1
    [upload_content_length] => 44
    [starttransfer_time] => 0.708674
    [redirect_time] => 0
    [redirect_url] => 
    [primary_ip] => 52.24.36.22
    [certinfo] => Array
        (
        )

    [primary_port] => 80
    [local_ip] => x.x.x.x
    [local_port] => 42258
    [http_version] => 2
    [protocol] => 1
    [ssl_verifyresult] => 0
    [scheme] => HTTP
    [appconnect_time_us] => 0
    [connect_time_us] => 214726
    [namelookup_time_us] => 29364
    [pretransfer_time_us] => 214822
    [redirect_time_us] => 0
    [starttransfer_time_us] => 708674
    [total_time_us] => 708746
)

[2021/04/03 09:29:40] Step getMetaData +OK
[2021/04/03 09:29:40] Execute handler (onInstallStep): Array
(
    [result] => Array
        (
            [core] => Array
                (
                    [hash] => 5189f003c9c9dd818c1b37fabe66f8e5
                    [build] => 471
                    [uhash] => 09e97b374096a78701452e3faa8ceba1
                )

            [plugins] => Array
                (
                )

            [themes] => Array
                (
                )

        )

)

.============================ POST REQUEST ==========================.
[2021/04/03 09:29:40] Postback payload: Array
(
    [step] => downloadCore
    [meta] => Array
        (
            [core] => Array
                (
                    [hash] => 5189f003c9c9dd818c1b37fabe66f8e5
                    [build] => 471
                    [uhash] => 09e97b374096a78701452e3faa8ceba1
                )

        )

    [handler] => onInstallStep
)

[2021/04/03 09:29:40] Install step: downloadCore
[2021/04/03 09:32:46] Saving to file (core): /usr/share/nginx/html/install_files/temp/a74ad8dfacd4f985eb3977517615ce25.arc
[2021/04/03 09:32:46] Step downloadCore +OK
[2021/04/03 09:32:46] Execute handler (onInstallStep): Array
(
    [result] => 
)

.============================ POST REQUEST ==========================.
[2021/04/03 09:32:46] Postback payload: Array
(
    [step] => extractCore
    [meta] => Array
        (
            [core] => Array
                (
                    [hash] => 5189f003c9c9dd818c1b37fabe66f8e5
                    [build] => 471
                    [uhash] => 09e97b374096a78701452e3faa8ceba1
                )

        )

    [handler] => onInstallStep
)

[2021/04/03 09:32:46] Install step: extractCore
[2021/04/03 09:32:46] Extracting file (core): a74ad8dfacd4f985eb3977517615ce25.arc
[2021/04/03 09:32:47] Step extractCore +OK
[2021/04/03 09:32:47] Execute handler (onInstallStep): Array
(
    [result] => 1
)

.============================ POST REQUEST ==========================.
[2021/04/03 09:32:47] Postback payload: Array
(
    [step] => setupConfig
    [meta] => Array
        (
            [core] => Array
                (
                    [hash] => 5189f003c9c9dd818c1b37fabe66f8e5
                    [build] => 471
                    [uhash] => 09e97b374096a78701452e3faa8ceba1
                )

        )

    [db_type] => mysql
    [db_host] => localhost
    [db_port] => 3306
    [db_name] => octoberdb
    [db_user] => octoberdb
    [db_pass] => *******
    [admin_first_name] => Admin
    [admin_last_name] => Person
    [admin_email] => *******@*****.com
    [admin_login] => admin
    [admin_password] => *******
    [admin_confirm_password] => *******
    [backend_uri] => /backend
    [encryption_code] => *******
    [file_mask] => 644
    [folder_mask] => 755
    [handler] => onInstallStep
)

[2021/04/03 09:32:47] Install step: setupConfig

```

**Comment by daftspunk** [comment]
PHP 8 is not currently supported by the mainstream copy of October CMS (v1.0). There are many libraries that are incompatible with the latest changes to PHP.

We are working hard to have this solved in the next couple of weeks. For now, you can use PHP 8 with composer

```
composer create-project october/october myoctober
```

This will deliver the v1.1 version that has been tested with PHP 8. Hope this helps
