### ISSUE TITLE
Composer Installation with PHP 8.1.8 fail

### ISSUE THREAD

**Issue by DavidBrogli** [octobercms/october#5652]
OctoberCMS cannot be installed via Composer on a system running PHP 8.1.8. The error message below appears.

It works on PHP 8.0.21.

Steps:
composer create-project october/october web (work)
php artisan october:install (fail)

```
web@plesk001:~/httpdocs$ php artisan october:install
PHP Fatal error:  During inheritance of ArrayAccess: Uncaught ErrorException: Return type of Illuminate\Support\Collection::offsetExists($key) should either be compatible with ArrayAccess::offsetExists(mixed $offset): bool, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /var/www/vhosts/web/httpdocs/vendor/laravel/framework/src/Illuminate/Support/Collection.php:1277
Stack trace:
#0 /var/www/vhosts/web/httpdocs/vendor/laravel/framework/src/Illuminate/Support/Collection.php(11): Illuminate\Foundation\Bootstrap\HandleExceptions->handleError()
#1 /var/www/vhosts/web/httpdocs/vendor/composer/ClassLoader.php(571): include('...')
#2 /var/www/vhosts/web/httpdocs/vendor/composer/ClassLoader.php(428): Composer\Autoload\includeFile()
#3 /var/www/vhosts/web/httpdocs/vendor/october/rain/src/Support/Collection.php(11): Composer\Autoload\ClassLoader->loadClass()
#4 /var/www/vhosts/web/httpdocs/vendor/composer/ClassLoader.php(571): include('...')
#5 /var/www/vhosts/web/httpdocs/vendor/composer/ClassLoader.php(428): Composer\Autoload\includeFile()
#6 /var/www/vhosts/web/httpdocs/vendor/october/rain/src/Support/helpers.php(265): Composer\Autoload\ClassLoader->loadClass()
#7 /var/www/vhosts/web/httpdocs/vendor/laravel/framework/src/Illuminate/Foundation/PackageManifest.php(89): collect()
#8 /var/www/vhosts/web/httpdocs/vendor/laravel/framework/src/Illuminate/Foundation/PackageManifest.php(78): Illuminate\Foundation\PackageManifest->config()
#9 /var/www/vhosts/web/httpdocs/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/RegisterFacades.php(26): Illuminate\Foundation\PackageManifest->aliases()
#10 /var/www/vhosts/web/httpdocs/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(219): Illuminate\Foundation\Bootstrap\RegisterFacades->bootstrap()
#11 /var/www/vhosts/web/httpdocs/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(320): Illuminate\Foundation\Application->bootstrapWith()
#12 /var/www/vhosts/web/httpdocs/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(129): Illuminate\Foundation\Console\Kernel->bootstrap()
#13 /var/www/vhosts/web/httpdocs/artisan(35): Illuminate\Foundation\Console\Kernel->handle()
#14 {main} in /var/www/vhosts/web/httpdocs/vendor/laravel/framework/src/Illuminate/Support/Collection.php on line 11

In Collection.php line 11:

  During inheritance of ArrayAccess: Uncaught ErrorException: Return type of Illuminate\Support\Collection::offsetExi
  sts($key) should either be compatible with ArrayAccess::offsetExists(mixed $offset): bool, or the #[\ReturnTypeWill
  Change] attribute should be used to temporarily suppress the notice in /var/www/vhosts/web/httpdocs/ven
  dor/laravel/framework/src/Illuminate/Support/Collection.php:1277
  Stack trace:
  #0 /var/www/vhosts/web/httpdocs/vendor/laravel/framework/src/Illuminate/Support/Collection.php(11): Ill
  uminate\Foundation\Bootstrap\HandleExceptions->handleError()
  #1 /var/www/vhosts/web/httpdocs/vendor/composer/ClassLoader.php(571): include('...')
  #2 /var/www/vhosts/web/httpdocs/vendor/composer/ClassLoader.php(428): Composer\Autoload\includeFile()
  #3 /var/www/vhosts/web/httpdocs/vendor/october/rain/src/Support/Collection.php(11): Composer\Autoload\C
  lassLoader->loadClass()
  #4 /var/www/vhosts/web/httpdocs/vendor/composer/ClassLoader.php(571): include('...')
  #5 /var/www/vhosts/web/httpdocs/vendor/composer/ClassLoader.php(428): Composer\Autoload\includeFile()
  #6 /var/www/vhosts/web/httpdocs/vendor/october/rain/src/Support/helpers.php(265): Composer\Autoload\Cla
  ssLoader->loadClass()
  #7 /var/www/vhosts/web/httpdocs/vendor/laravel/framework/src/Illuminate/Foundation/PackageManifest.php(
  89): collect()
  #8 /var/www/vhosts/web/httpdocs/vendor/laravel/framework/src/Illuminate/Foundation/PackageManifest.php(
  78): Illuminate\Foundation\PackageManifest->config()
  #9 /var/www/vhosts/web/httpdocs/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/RegisterFa
  cades.php(26): Illuminate\Foundation\PackageManifest->aliases()
  #10 /var/www/vhosts/web/httpdocs/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(219
  ): Illuminate\Foundation\Bootstrap\RegisterFacades->bootstrap()
  #11 /var/www/vhosts/web/httpdocs/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(
  320): Illuminate\Foundation\Application->bootstrapWith()
  #12 /var/www/vhosts/web/httpdocs/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(
  129): Illuminate\Foundation\Console\Kernel->bootstrap()
  #13 /var/www/vhosts/web/httpdocs/artisan(35): Illuminate\Foundation\Console\Kernel->handle()
  #14 {main}
```

**Comment by daftspunk** [comment]
Hi @DavidBrogli 

That is accurate. October v2 does not support PHP 8.1 since it uses Laravel 6. The options are to use PHP 8.0 or [install October CMS 3.0](https://docs.octobercms.com/3.x/setup/installation.html), which is slated for a stable release soon.
