### ISSUE TITLE
Call to undefined method RainLab\Translate\Models\Message::setContext() when try to submit a message form

### ISSUE THREAD

**Issue by haralake** [octobercms/october#5664]
On latest Octobercms v3.1.3 with translate plugin v2.0 (Multisite), when try to submit a message using contact form (Blake Jones Magic forms plugin) i get this error:

`"Call to undefined method RainLab\Translate\Models\Message::setContext()" on line 71 of /var/www/octobercms3.local/htdocs/vendor/laravel/framework/src/Illuminate/Support/Traits/ForwardsCalls.php"`

my composer:
```
.....
    "require": {
        "php": "^8.0.2",
        "october/rain": "^3.1",
        "laravel/framework": "^9.0",
        "october/all": "^3.1",
        "rainlab/user-plugin": "^1.6",
        "rainlab/blog-plugin": "^1.6",
        "rainlab/mailchimp-plugin": "^1.0",
        "rainlab/translate-plugin": "^2.0",
        "rainlab/pages-plugin": "^1.5",
        "blakejones/magicforms-plugin": "^1.6"
    },
......
```

**Comment by daftspunk** [comment]
Hi @haralake 

I need to see the full stack trace. The error message doesn't give enough information. In Translate 2.0, the `RainLab\Translate\Models\Message` class is replaced by a combination of `RainLab\Translate\Classes\Message` and the `Site` global.

Here is a link to the magic forms repo, however, this doesn't appear to be the cause of the issue: https://github.com/blakej115/magic-forms

I hope this helps.

**Comment by haralake** [comment]
I will report the error to the plugin creator. However, I am putting up the full stack trace here as well just for reference. Thanks.

```
BadMethodCallException: Call to undefined method RainLab\Translate\Models\Message::setContext() in /var/www/octobercms.local/htdocs/vendor/laravel/framework/src/Illuminate/Support/Traits/ForwardsCalls.php:71
Stack trace:
#0 /var/www/octobercms.local/htdocs/vendor/laravel/framework/src/Illuminate/Support/Traits/ForwardsCalls.php(36): Illuminate\Database\Eloquent\Model::throwBadMethodCallException()
#1 /var/www/octobercms.local/htdocs/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(2230): Illuminate\Database\Eloquent\Model->forwardCallTo()
#2 /var/www/octobercms.local/htdocs/vendor/october/rain/src/Extension/ExtendableTrait.php(511): Illuminate\Database\Eloquent\Model->__call()
#3 /var/www/octobercms.local/htdocs/vendor/october/rain/src/Database/Model.php(305): October\Rain\Database\Model->extendableCall()
#4 /var/www/octobercms.local/htdocs/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(2242): October\Rain\Database\Model->__call()
#5 /var/www/octobercms.local/htdocs/plugins/blakejones/magicforms/classes/MagicForm.php(71): Illuminate\Database\Eloquent\Model::__callStatic()
#6 /var/www/octobercms.local/htdocs/modules/system/traits/DependencyMaker.php(29): BlakeJones\MagicForms\Classes\MagicForm->onFormSubmit()
#7 /var/www/octobercms.local/htdocs/modules/cms/classes/ComponentBase.php(197): Cms\Classes\ComponentBase->makeCallMethod()
#8 /var/www/octobercms.local/htdocs/modules/cms/classes/Controller.php(862): Cms\Classes\ComponentBase->runAjaxHandler()
#9 /var/www/octobercms.local/htdocs/modules/cms/classes/Controller.php(714): Cms\Classes\Controller->runAjaxHandler()
#10 /var/www/octobercms.local/htdocs/modules/cms/classes/Controller.php(365): Cms\Classes\Controller->execAjaxHandlers()
#11 /var/www/octobercms.local/htdocs/modules/cms/classes/Controller.php(218): Cms\Classes\Controller->runPage()
#12 /var/www/octobercms.local/htdocs/modules/cms/classes/CmsController.php(64): Cms\Classes\Controller->run()
#13 /var/www/octobercms.local/htdocs/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): Cms\Classes\CmsController->run()
#14 /var/www/octobercms.local/htdocs/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(43): Illuminate\Routing\Controller->callAction()
#15 /var/www/octobercms.local/htdocs/vendor/laravel/framework/src/Illuminate/Routing/Route.php(259): Illuminate\Routing\ControllerDispatcher->dispatch()
#16 /var/www/octobercms.local/htdocs/vendor/laravel/framework/src/Illuminate/Routing/Route.php(204): Illuminate\Routing\Route->runController()
#17 /var/www/octobercms.local/htdocs/vendor/laravel/framework/src/Illuminate/Routing/Router.php(725): Illuminate\Routing\Route->run()
#18 /var/www/octobercms.local/htdocs/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(141): Illuminate\Routing\Router->Illuminate\Routing\{closure}()
#19 /var/www/octobercms.local/htdocs/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(50): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#20 /var/www/octobercms.local/htdocs/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\Routing\Middleware\SubstituteBindings->handle()
#21 /var/www/octobercms.local/htdocs/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#22 /var/www/octobercms.local/htdocs/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\View\Middleware\ShareErrorsFromSession->handle()
#23 /var/www/octobercms.local/htdocs/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(121): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#24 /var/www/octobercms.local/htdocs/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(64): Illuminate\Session\Middleware\StartSession->handleStatefulRequest()
#25 /var/www/octobercms.local/htdocs/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\Session\Middleware\StartSession->handle()
#26 /var/www/octobercms.local/htdocs/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#27 /var/www/octobercms.local/htdocs/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse->handle()
#28 /var/www/octobercms.local/htdocs/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(67): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#29 /var/www/octobercms.local/htdocs/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\Cookie\Middleware\EncryptCookies->handle()
#30 /var/www/octobercms.local/htdocs/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(116): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#31 /var/www/octobercms.local/htdocs/vendor/laravel/framework/src/Illuminate/Routing/Router.php(726): Illuminate\Pipeline\Pipeline->then()
#32 /var/www/octobercms.local/htdocs/vendor/laravel/framework/src/Illuminate/Routing/Router.php(703): Illuminate\Routing\Router->runRouteWithinStack()
#33 /var/www/octobercms.local/htdocs/vendor/laravel/framework/src/Illuminate/Routing/Router.php(667): Illuminate\Routing\Router->runRoute()
#34 /var/www/octobercms.local/htdocs/vendor/october/rain/src/Router/CoreRouter.php(31): Illuminate\Routing\Router->dispatchToRoute()
#35 /var/www/octobercms.local/htdocs/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(190): October\Rain\Router\CoreRouter->dispatch()
#36 /var/www/octobercms.local/htdocs/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(141): Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}()
#37 /var/www/octobercms.local/htdocs/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/PreventRequestsDuringMaintenance.php(86): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#38 /var/www/octobercms.local/htdocs/vendor/october/rain/src/Foundation/Http/Middleware/CheckForMaintenanceMode.php(23): Illuminate\Foundation\Http\Middleware\PreventRequestsDuringMaintenance->handle()
#39 /var/www/octobercms.local/htdocs/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): October\Rain\Foundation\Http\Middleware\CheckForMaintenanceMode->handle()
#40 /var/www/octobercms.local/htdocs/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(116): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#41 /var/www/octobercms.local/htdocs/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(165): Illuminate\Pipeline\Pipeline->then()
#42 /var/www/octobercms.local/htdocs/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(134): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter()
#43 /var/www/octobercms.local/htdocs/index.php(43): Illuminate\Foundation\Http\Kernel->handle()
#44 {main}
```
