### ISSUE TITLE
Installing October from scratch

### ISSUE THREAD

**Issue by winstonderek** [octobercms/october#5792]
Hi, I had this issue on a already running october CMS project, so I decided to install a fresh copy of october CMS, and add the plugins an themes. 

I'm installing this in a Linux machine powered by plesk.

Yesterday everything was working as expected, and never had a issue with october cms like this before and I have been using it for 4 years now.

In my local, this same projects runs ok, it's just in the server that I get this message, eather if i try a new install or with the not anymore working app already deployed on the server.

Can anyone help me? 

```
Enter a valid License Key to proceed.

 License Key:
 > ******(here my licence)

PHP Fatal error:  Uncaught Error: Call to undefined method Event::getFacadeApplication() in /var/www/vhosts/intranet.yovivo.nl/httpdocs/vendor/october/rain/src/Foundation/Exception/Handler.php:253
Stack trace:
#0 /var/www/vhosts/intranet.yovivo.nl/httpdocs/vendor/october/rain/src/Foundation/Exception/Handler.php(50): October\Rain\Foundation\Exception\Handler->hasBootedEvents()
#1 /var/www/vhosts/intranet.yovivo.nl/httpdocs/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(198): October\Rain\Foundation\Exception\Handler->report()
#2 /var/www/vhosts/intranet.yovivo.nl/httpdocs/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(270): Illuminate\Foundation\Bootstrap\HandleExceptions->handleException()
#3 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->Illuminate\Foundation\Bootstrap\{closure}()
#4 {main}
  thrown in /var/www/vhosts/intranet.yovivo.nl/httpdocs/vendor/october/rain/src/Foundation/Exception/Handler.php on line 253
PHP Fatal error:  Uncaught Error: Call to undefined method Event::getFacadeApplication() in /var/www/vhosts/intranet.yovivo.nl/httpdocs/vendor/october/rain/src/Foundation/Exception/Handler.php:253
Stack trace:
#0 /var/www/vhosts/intranet.yovivo.nl/httpdocs/vendor/october/rain/src/Foundation/Exception/Handler.php(50): October\Rain\Foundation\Exception\Handler->hasBootedEvents()
#1 /var/www/vhosts/intranet.yovivo.nl/httpdocs/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(198): October\Rain\Foundation\Exception\Handler->report()
#2 /var/www/vhosts/intranet.yovivo.nl/httpdocs/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(246): Illuminate\Foundation\Bootstrap\HandleExceptions->handleException()
#3 /var/www/vhosts/intranet.yovivo.nl/httpdocs/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(270): Illuminate\Foundation\Bootstrap\HandleExceptions->handleShutdown()
#4 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->Illuminate\Foundation\Bootstrap\{closure}()
#5 {main}
  thrown in /var/www/vhosts/intranet.yovivo.nl/httpdocs/vendor/october/rain/src/Foundation/Exception/Handler.php on line 253
```

**Comment by winstonderek** [comment]
Seems that the PHP version was creating errors in the composer

**Comment by winstonderek** [comment]
not really stable

**Comment by daftspunk** [comment]
This can happen when the CLI uses a different PHP version to the PHP version used by your web server.

**Comment by winstonderek** [comment]
Could also be the composer -v I think, they have to be exactly the same version. seems that you really need to have the same PHP and composer Version when you deploy and you serve the app. Even if it's the same PHP 8 (8.1 or 8.3) will have impact.

**Comment by proteo** [comment]
Hi there. I am having the exact same issue, and can't figure out what is wrong. I have tried different versions of PHP (currently on 8.2.27 and composer (now using 2.8.4) but the error isn't going away. This is a fresh install using Docker on my local computer.

Any help would be appreciated.
