### ISSUE TITLE
Critical fail when updating with php artisan october:update

### ISSUE THREAD

**Issue by Dahfrenk** [octobercms/october#5801]
I have an issue when attempting to update October CMS 3.6.18 to the newest version using the october:update command. I always update sites with the terminal but this time it crashed. It crashes at a point where the update process empties the whole modules folder. In order to recover from this crash I have to copy the original modules and vendor folder back.

**The error generating is as following:**
```
[16-Jun-2024 21:38:25 UTC] PHP Fatal error:  Uncaught Error: Class "System\Classes\ErrorHandler" not found in /home/waldorf/public_html/domain.com/modules/system/ServiceProvider.php:252
Stack trace:
#0 /home/waldorf/public_html/domain.com/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php(421): System\ServiceProvider->System\{closure}(Object(Error))
#1 /home/waldorf/public_html/domain.com/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php(249): Illuminate\Events\Dispatcher->Illuminate\Events\{closure}('exception.befor...', Array)
#2 /home/waldorf/public_html/domain.com/vendor/october/rain/src/Events/PriorityDispatcher.php(112): Illuminate\Events\Dispatcher->dispatch('exception.befor...', Array, true)
#3 /home/waldorf/public_html/domain.com/vendor/october/rain/src/Events/PriorityDispatcher.php(79): October\Rain\Events\PriorityDispatcher->fireEvent('exception.befor...', Array, true)
#4 /home/waldorf/public_html/domain.com/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(338): October\Rain\Events\PriorityDispatcher->fire('exception.befor...', Array, true)
#5 /home/waldorf/public_html/domain.com/vendor/october/rain/src/Foundation/Exception/Handler.php(66): Illuminate\Support\Facades\Facade::__callStatic('fire', Array)
#6 /home/waldorf/public_html/domain.com/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(198): October\Rain\Foundation\Exception\Handler->report(Object(Error))
#7 /home/waldorf/public_html/domain.com/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(270): Illuminate\Foundation\Bootstrap\HandleExceptions->handleException(Object(Error))
#8 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->Illuminate\Foundation\Bootstrap\{closure}(Object(Error))
#9 {main}
  thrown in /home/waldorf/public_html/domain.com/modules/system/ServiceProvider.php on line 252
[16-Jun-2024 21:38:25 UTC] PHP Fatal error:  Uncaught Error: Class "System\Classes\ErrorHandler" not found in /home/waldorf/public_html/domain.com/modules/system/ServiceProvider.php:252
Stack trace:
#0 /home/waldorf/public_html/domain.com/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php(421): System\ServiceProvider->System\{closure}(Object(Symfony\Component\ErrorHandler\Error\FatalError))
#1 /home/waldorf/public_html/domain.com/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php(249): Illuminate\Events\Dispatcher->Illuminate\Events\{closure}('exception.befor...', Array)
#2 /home/waldorf/public_html/domain.com/vendor/october/rain/src/Events/PriorityDispatcher.php(112): Illuminate\Events\Dispatcher->dispatch('exception.befor...', Array, true)
#3 /home/waldorf/public_html/domain.com/vendor/october/rain/src/Events/PriorityDispatcher.php(79): October\Rain\Events\PriorityDispatcher->fireEvent('exception.befor...', Array, true)
#4 /home/waldorf/public_html/domain.com/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(338): October\Rain\Events\PriorityDispatcher->fire('exception.befor...', Array, true)
#5 /home/waldorf/public_html/domain.com/vendor/october/rain/src/Foundation/Exception/Handler.php(66): Illuminate\Support\Facades\Facade::__callStatic('fire', Array)
#6 /home/waldorf/public_html/domain.com/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(198): October\Rain\Foundation\Exception\Handler->report(Object(Symfony\Component\ErrorHandler\Error\FatalError))
#7 /home/waldorf/public_html/domain.com/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(246): Illuminate\Foundation\Bootstrap\HandleExceptions->handleException(Object(Symfony\Component\ErrorHandler\Error\FatalError))
#8 /home/waldorf/public_html/domain.com/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(270): Illuminate\Foundation\Bootstrap\HandleExceptions->handleShutdown()
#9 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->Illuminate\Foundation\Bootstrap\{closure}()
#10 {main}
  thrown in /home/waldorf/public_html/domain.com/modules/system/ServiceProvider.php on line 252
```

**Within the terminal the following happens**
<img width="567" alt="Scherm­afbeelding 2024-06-16 om 23 38 44" src="https://github.com/octobercms/october/assets/11441869/6ccf282f-0816-4d58-a15d-c9ab7cebd824">
<img width="505" alt="Scherm­afbeelding 2024-06-16 om 23 39 00" src="https://github.com/octobercms/october/assets/11441869/57742709-1cb4-4f21-b9d2-3716c8852ed9">
<img width="376" alt="Scherm­afbeelding 2024-06-16 om 23 39 24" src="https://github.com/octobercms/october/assets/11441869/166e92b7-6018-45e1-9f12-84b808f961a7">

**The error message when opening the website:**
Missing vendor files, try running "composer install" to install October CMS

When I restore the files and update through the CMS update interface, the update works just fine. It is just updating trough the terminal that causes this. I have no clue what causes this.

**Comment by daftspunk** [comment]
Hi @Dahfrenk 

This is interesting. These all appear to be general errors. 

Does it happen when you run `composer update` instead?

**Comment by daftspunk** [comment]
Cleaning up issues.
