### ISSUE TITLE
ApplicationException: Invalid file path specified

### ISSUE THREAD

**Issue by chrisvidal** [octobercms/october#5808]
`{{ data.file | media }}` generates an exception event though the rendered path is correct.

Any idea what could be wrong ?
It was working fine 2 years ago with OC v2, maybe it creates this error since OC v3, no idea yet.

thanks

```
ApplicationException: Invalid file path specified: '/storage/app/media/products/Product%20Factsheets/Astrea%20III%20Product%20Factsheet%20v20Jan21.pdf'. in /Users/christophevidal/Sites/oc-azalea2[/modules/media/classes/MediaLibrary.php:497](javascript:)
```

```
ApplicationException: Invalid file path specified: '/storage/app/media/products/Product%20Factsheets/Astrea%20III%20Product%20Factsheet%20v20Jan21.pdf'. in /Users/christophevidal/Sites/oc-azalea2/modules/media/classes/MediaLibrary.php:497
Stack trace:
#0 /Users/christophevidal/Sites/oc-azalea2/modules/media/classes/MediaLibrary.php(548): Media\Classes\MediaLibrary::validatePath('/storage/app/me...')
#1 /Users/christophevidal/Sites/oc-azalea2/modules/media/classes/MediaLibrary.php(538): Media\Classes\MediaLibrary->getPathUrl('/storage/app/me...')
#2 /Users/christophevidal/Sites/oc-azalea2/modules/system/classes/MarkupExtensionItem.php(166): Media\Classes\MediaLibrary::url('/storage/app/me...')
#3 /Users/christophevidal/Sites/oc-azalea2/storage/cms/twig/10/10bcf8727e3a16dd0f29fe027a7b7087.php(55): System\Classes\MarkupExtensionItem->System\Classes\{closure}('/storage/app/me...')
#4 /Users/christophevidal/Sites/oc-azalea2/vendor/twig/twig/src/Template.php(394): __TwigTemplate_813db9845d8508a29f32947ca9dcb6a2->doDisplay(Array, Array)
#5 /Users/christophevidal/Sites/oc-azalea2/vendor/twig/twig/src/Template.php(367): Twig\Template->displayWithErrorHandling(Array, Array)
#6 /Users/christophevidal/Sites/oc-azalea2/vendor/twig/twig/src/Template.php(379): Twig\Template->display(Array)
#7 /Users/christophevidal/Sites/oc-azalea2/vendor/twig/twig/src/TemplateWrapper.php(38): Twig\Template->render(Array)
#8 /Users/christophevidal/Sites/oc-azalea2/modules/cms/classes/controller/HasRenderers.php(242): Twig\TemplateWrapper->render(Array)
#9 /Users/christophevidal/Sites/oc-azalea2/modules/cms/twig/Extension.php(154): Cms\Classes\Controller->renderPartial('azIPO::prospect...', Array, true)
#10 /Users/christophevidal/Sites/oc-azalea2/storage/cms/twig/a6/a645768e9db786cea4dfcf551a75f5dd.php(57): Cms\Twig\Extension->partialFunction('azIPO::prospect...', Array, true)
#11 /Users/christophevidal/Sites/oc-azalea2/vendor/twig/twig/src/Template.php(394): __TwigTemplate_7e0e671872d46b3c2ff70e700dc926b9->doDisplay(Array, Array)
#12 /Users/christophevidal/Sites/oc-azalea2/vendor/twig/twig/src/Template.php(367): Twig\Template->displayWithErrorHandling(Array, Array)
#13 /Users/christophevidal/Sites/oc-azalea2/vendor/twig/twig/src/Template.php(379): Twig\Template->display(Array)
#14 /Users/christophevidal/Sites/oc-azalea2/vendor/twig/twig/src/TemplateWrapper.php(38): Twig\Template->render(Array)
#15 /Users/christophevidal/Sites/oc-azalea2/modules/cms/classes/controller/HasRenderers.php(242): Twig\TemplateWrapper->render(Array)
#16 /Users/christophevidal/Sites/oc-azalea2/modules/cms/twig/Extension.php(154): Cms\Classes\Controller->renderPartial('azIPO::prospect...', Array, true)
#17 /Users/christophevidal/Sites/oc-azalea2/storage/cms/twig/24/2487764f590829a6b48550092da62315.php(145): Cms\Twig\Extension->partialFunction('azIPO::prospect...', Array, true)
#18 /Users/christophevidal/Sites/oc-azalea2/vendor/twig/twig/src/Template.php(394): __TwigTemplate_d47b4408c5620f44b247096af71331e5->doDisplay(Array, Array)
#19 /Users/christophevidal/Sites/oc-azalea2/vendor/twig/twig/src/Template.php(367): Twig\Template->displayWithErrorHandling(Array, Array)
#20 /Users/christophevidal/Sites/oc-azalea2/vendor/twig/twig/src/Template.php(379): Twig\Template->display(Array)
#21 /Users/christophevidal/Sites/oc-azalea2/vendor/twig/twig/src/TemplateWrapper.php(38): Twig\Template->render(Array)
#22 /Users/christophevidal/Sites/oc-azalea2/modules/cms/classes/controller/HasRenderers.php(242): Twig\TemplateWrapper->render(Array)
#23 /Users/christophevidal/Sites/oc-azalea2/modules/cms/classes/controller/HasRenderers.php(391): Cms\Classes\Controller->renderPartial('azIPO::default', Array, false)
#24 /Users/christophevidal/Sites/oc-azalea2/modules/cms/twig/Extension.php(194): Cms\Classes\Controller->renderComponent('azIPO', Array)
#25 /Users/christophevidal/Sites/oc-azalea2/storage/cms/twig/3a/3addec6354fa7109821870b34718fdf9.php(38): Cms\Twig\Extension->componentFunction('azIPO', Array)
#26 /Users/christophevidal/Sites/oc-azalea2/vendor/twig/twig/src/Template.php(394): __TwigTemplate_be1d3d6385d13639aa6359594a1ddf62->doDisplay(Array, Array)
#27 /Users/christophevidal/Sites/oc-azalea2/vendor/twig/twig/src/Template.php(367): Twig\Template->displayWithErrorHandling(Array, Array)
#28 /Users/christophevidal/Sites/oc-azalea2/vendor/twig/twig/src/Template.php(379): Twig\Template->display(Array)
#29 /Users/christophevidal/Sites/oc-azalea2/vendor/twig/twig/src/TemplateWrapper.php(38): Twig\Template->render(Array)
#30 /Users/christophevidal/Sites/oc-azalea2/modules/cms/classes/controller/HasRenderers.php(83): Twig\TemplateWrapper->render(Array)
#31 /Users/christophevidal/Sites/oc-azalea2/modules/cms/classes/Controller.php(414): Cms\Classes\Controller->renderPageContents()
#32 /Users/christophevidal/Sites/oc-azalea2/modules/cms/classes/Controller.php(219): Cms\Classes\Controller->runPage(Object(Cms\Classes\Page))
#33 /Users/christophevidal/Sites/oc-azalea2/modules/cms/classes/CmsController.php(71): Cms\Classes\Controller->run('a7/overview/def...')
#34 /Users/christophevidal/Sites/oc-azalea2/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): Cms\Classes\CmsController->run('a7/overview/def...')
#35 /Users/christophevidal/Sites/oc-azalea2/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(43): Illuminate\Routing\Controller->callAction('run', Array)
#36 /Users/christophevidal/Sites/oc-azalea2/vendor/laravel/framework/src/Illuminate/Routing/Route.php(260): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(Cms\Classes\CmsController), 'run')
#37 /Users/christophevidal/Sites/oc-azalea2/vendor/laravel/framework/src/Illuminate/Routing/Route.php(205): Illuminate\Routing\Route->runController()
#38 /Users/christophevidal/Sites/oc-azalea2/vendor/laravel/framework/src/Illuminate/Routing/Router.php(798): Illuminate\Routing\Route->run()
#39 /Users/christophevidal/Sites/oc-azalea2/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(141): Illuminate\Routing\Router->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#40 /Users/christophevidal/Sites/oc-azalea2/plugins/vdlp/twofactorauthentication/classes/TwoFactorMiddleware.php(57): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#41 /Users/christophevidal/Sites/oc-azalea2/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Vdlp\TwoFactorAuthentication\Classes\TwoFactorMiddleware->handle(Object(Illuminate\Http\Request), Object(Closure))
#42 /Users/christophevidal/Sites/oc-azalea2/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(50): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#43 /Users/christophevidal/Sites/oc-azalea2/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\Routing\Middleware\SubstituteBindings->handle(Object(Illuminate\Http\Request), Object(Closure))
#44 /Users/christophevidal/Sites/oc-azalea2/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#45 /Users/christophevidal/Sites/oc-azalea2/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\View\Middleware\ShareErrorsFromSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#46 /Users/christophevidal/Sites/oc-azalea2/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(121): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#47 /Users/christophevidal/Sites/oc-azalea2/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(64): Illuminate\Session\Middleware\StartSession->handleStatefulRequest(Object(Illuminate\Http\Request), Object(Illuminate\Session\Store), Object(Closure))
#48 /Users/christophevidal/Sites/oc-azalea2/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\Session\Middleware\StartSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#49 /Users/christophevidal/Sites/oc-azalea2/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#50 /Users/christophevidal/Sites/oc-azalea2/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse->handle(Object(Illuminate\Http\Request), Object(Closure))
#51 /Users/christophevidal/Sites/oc-azalea2/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(67): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#52 /Users/christophevidal/Sites/oc-azalea2/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\Cookie\Middleware\EncryptCookies->handle(Object(Illuminate\Http\Request), Object(Closure))
#53 /Users/christophevidal/Sites/oc-azalea2/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(116): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#54 /Users/christophevidal/Sites/oc-azalea2/vendor/laravel/framework/src/Illuminate/Routing/Router.php(799): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#55 /Users/christophevidal/Sites/oc-azalea2/vendor/laravel/framework/src/Illuminate/Routing/Router.php(776): Illuminate\Routing\Router->runRouteWithinStack(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request))
#56 /Users/christophevidal/Sites/oc-azalea2/vendor/laravel/framework/src/Illuminate/Routing/Router.php(740): Illuminate\Routing\Router->runRoute(Object(Illuminate\Http\Request), Object(Illuminate\Routing\Route))
#57 /Users/christophevidal/Sites/oc-azalea2/vendor/october/rain/src/Router/CoreRouter.php(32): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#58 /Users/christophevidal/Sites/oc-azalea2/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(190): October\Rain\Router\CoreRouter->dispatch(Object(Illuminate\Http\Request))
#59 /Users/christophevidal/Sites/oc-azalea2/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(141): Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}(Object(Illuminate\Http\Request))
#60 /Users/christophevidal/Sites/oc-azalea2/plugins/zaxbux/securityheaders/classes/SecurityHeaderMiddleware.php(20): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#61 /Users/christophevidal/Sites/oc-azalea2/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Zaxbux\SecurityHeaders\Classes\SecurityHeaderMiddleware->handle(Object(Illuminate\Http\Request), Object(Closure))
#62 /Users/christophevidal/Sites/oc-azalea2/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/PreventRequestsDuringMaintenance.php(86): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#63 /Users/christophevidal/Sites/oc-azalea2/vendor/october/rain/src/Foundation/Http/Middleware/CheckForMaintenanceMode.php(23): Illuminate\Foundation\Http\Middleware\PreventRequestsDuringMaintenance->handle(Object(Illuminate\Http\Request), Object(Closure))
#64 /Users/christophevidal/Sites/oc-azalea2/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): October\Rain\Foundation\Http\Middleware\CheckForMaintenanceMode->handle(Object(Illuminate\Http\Request), Object(Closure))
#65 /Users/christophevidal/Sites/oc-azalea2/plugins/vdlp/redirect/classes/RedirectMiddleware.php(78): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#66 /Users/christophevidal/Sites/oc-azalea2/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Vdlp\Redirect\Classes\RedirectMiddleware->handle(Object(Illuminate\Http\Request), Object(Closure))
#67 /Users/christophevidal/Sites/oc-azalea2/plugins/zaxbux/securityheaders/classes/NonceGeneratorMiddleware.php(22): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#68 /Users/christophevidal/Sites/oc-azalea2/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Zaxbux\SecurityHeaders\Classes\NonceGeneratorMiddleware->handle(Object(Illuminate\Http\Request), Object(Closure))
#69 /Users/christophevidal/Sites/oc-azalea2/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(116): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#70 /Users/christophevidal/Sites/oc-azalea2/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(165): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#71 /Users/christophevidal/Sites/oc-azalea2/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(134): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#72 /Users/christophevidal/Sites/oc-azalea2/index.php(43): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#73 /Users/christophevidal/.composer/vendor/laravel/valet/server.php(110): require('/Users/christop...')
#74 {main}
Next Twig\Error\RuntimeError: An exception has been thrown during the rendering of a template ("Invalid file path specified: '/storage/app/media/products/Product%20Factsheets/Astrea%20III%20Product%20Factsheet%20v20Jan21.pdf'.") in "/Users/christophevidal/Sites/oc-azalea2/plugins//voilaah/azalea/components/partials/prospectus_disclaimer.htm" at line 9. in /Users/christophevidal/Sites/oc-azalea2/vendor/twig/twig/src/Template.php:408
Stack trace:
```

**Comment by daftspunk** [comment]
It looks like an invalid path. The path should be:

```
{{ 'products/Product%20Factsheets/Astrea%20III%20Product%20Factsheet%20v20Jan21.pdf'|media }}
```

**Comment by chrisvidal** [comment]
oh damn, I didnt see that indeed !
After checking the twig `| media` was called twice in different files.

thanks a lot !
