### ISSUE TITLE
Backend cannot be displayed

### ISSUE THREAD

**Issue by charleslcso** [octobercms/october#5828]
Hello, I'm new to October CMS.

Got it installed, and everything went fine. Nice work!

Once I got into the /admin, it tells me that it is too simple and I should change it to something. 

I searched the web, and revised the value "admin" in /config/backend.php to "december". 

Now, both "/december" nor "/admin" will load.

What can I do to get the admin back? BTW, while the /admin was working, I updated it from 3.7.0 to 3.7.5.

**Comment by daftspunk** [comment]
Hi @charleslcso 

That's unusual. It should work just the same. Are you using Apache? If so, check that ModRewrite is enabled.

**Comment by charleslcso** [comment]
I’m using Nginx. 

When I use /admin, I get "something went wrong and the page cannot be displayed".
When I use /december, I get 404.

backend.php is back to using 'admin'.

One of the reasons could be that before it broke I tried to install 2 different themes, with both failed. It said something about octobercms.org error.

Then this issue comes up.

Oh, yes, the theme from that company broke admin.

`[2024-11-27 01:23:39] local.ERROR: PDOException: SQLSTATE[42P01]: Undefined table: 7 ERROR:  relation "ratmd_bloghub_comments" does not exist
LINE 1: select count(*) as aggregate from "ratmd_bloghub_comments" w...
                                          ^ in /var/www/html/myoctober/vendor/laravel/framework/src/Illuminate/Database/Connection.php:419
Stack trace:
#0 /var/www/html/myoctober/vendor/laravel/framework/src/Illuminate/Database/Connection.php(419): PDOStatement->execute()
#1 /var/www/html/myoctober/vendor/laravel/framework/src/Illuminate/Database/Connection.php(753): Illuminate\Database\Connection->Illuminate\Database\{closure}()
#2 /var/www/html/myoctober/vendor/laravel/framework/src/Illuminate/Database/Connection.php(720): Illuminate\Database\Connection->runQueryCallback()
#3 /var/www/html/myoctober/vendor/laravel/framework/src/Illuminate/Database/Connection.php(422): Illuminate\Database\Connection->run()
`

In the /themes folder, there is 'demo'. In /plugins, there are folders for each of the failed theme: rainlab and ratmd.

Removing both /plugins/rainlab and /plugins/ratmd fixed the 500 issue.

**Comment by daftspunk** [comment]
This looks like a migration table was missing 

`php artisan october:migrate`

Glad you got it sorted.
